/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.pokemmo.db.jooq.tables.Account;
import org.pokemmo.db.jooq.tables.AccountContext;
import org.pokemmo.db.jooq.tables.BlackList;
import org.pokemmo.db.jooq.tables.Character;
import org.pokemmo.db.jooq.tables.Container;
import org.pokemmo.db.jooq.tables.FriendList;
import org.pokemmo.db.jooq.tables.GameNode;
import org.pokemmo.db.jooq.tables.Inventory;
import org.pokemmo.db.jooq.tables.OnlineChatNodeServer;
import org.pokemmo.db.jooq.tables.OnlineGameNodeServer;
import org.pokemmo.db.jooq.tables.OwnedItem;
import org.pokemmo.db.jooq.tables.Pokemon;
import org.pokemmo.db.jooq.tables.PokemonDex;
import org.pokemmo.db.jooq.tables.ServerToken;
import org.pokemmo.db.jooq.tables.records.AccountContextRecord;
import org.pokemmo.db.jooq.tables.records.AccountRecord;
import org.pokemmo.db.jooq.tables.records.BlackListRecord;
import org.pokemmo.db.jooq.tables.records.CharacterRecord;
import org.pokemmo.db.jooq.tables.records.ContainerRecord;
import org.pokemmo.db.jooq.tables.records.FriendListRecord;
import org.pokemmo.db.jooq.tables.records.GameNodeRecord;
import org.pokemmo.db.jooq.tables.records.InventoryRecord;
import org.pokemmo.db.jooq.tables.records.OnlineChatNodeServerRecord;
import org.pokemmo.db.jooq.tables.records.OnlineGameNodeServerRecord;
import org.pokemmo.db.jooq.tables.records.OwnedItemRecord;
import org.pokemmo.db.jooq.tables.records.PokemonDexRecord;
import org.pokemmo.db.jooq.tables.records.PokemonRecord;
import org.pokemmo.db.jooq.tables.records.ServerTokenRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> ACCOUNT_ACCOUNT_NAME_KEY = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("account_account_name_key"), new TableField[] { Account.ACCOUNT.ACCOUNT_NAME }, true);
    public static final UniqueKey<AccountRecord> ACCOUNT_PKEY = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("account_pkey"), new TableField[] { Account.ACCOUNT.ACCOUNT_ID }, true);
    public static final UniqueKey<AccountContextRecord> ACCOUNT_CONTEXT_PKEY = Internal.createUniqueKey(AccountContext.ACCOUNT_CONTEXT, DSL.name("account_context_pkey"), new TableField[] { AccountContext.ACCOUNT_CONTEXT.ACCOUNT_ID }, true);
    public static final UniqueKey<BlackListRecord> BLACK_LIST_PKEY = Internal.createUniqueKey(BlackList.BLACK_LIST, DSL.name("black_list_pkey"), new TableField[] { BlackList.BLACK_LIST.PLAYER_ID }, true);
    public static final UniqueKey<CharacterRecord> CHARACTER_PKEY = Internal.createUniqueKey(Character.CHARACTER, DSL.name("character_pkey"), new TableField[] { Character.CHARACTER.ID }, true);
    public static final UniqueKey<ContainerRecord> CONTAINER_NAME_KEY = Internal.createUniqueKey(Container.CONTAINER, DSL.name("container_name_key"), new TableField[] { Container.CONTAINER.NAME }, true);
    public static final UniqueKey<ContainerRecord> CONTAINER_PKEY = Internal.createUniqueKey(Container.CONTAINER, DSL.name("container_pkey"), new TableField[] { Container.CONTAINER.ID }, true);
    public static final UniqueKey<FriendListRecord> FRIEND_LIST_PKEY = Internal.createUniqueKey(FriendList.FRIEND_LIST, DSL.name("friend_list_pkey"), new TableField[] { FriendList.FRIEND_LIST.PLAYER_ID }, true);
    public static final UniqueKey<GameNodeRecord> GAME_NODE_NODE_NAME_KEY = Internal.createUniqueKey(GameNode.GAME_NODE, DSL.name("game_node_node_name_key"), new TableField[] { GameNode.GAME_NODE.NODE_NAME }, true);
    public static final UniqueKey<GameNodeRecord> GAME_NODE_PKEY = Internal.createUniqueKey(GameNode.GAME_NODE, DSL.name("game_node_pkey"), new TableField[] { GameNode.GAME_NODE.NODE_ID }, true);
    public static final UniqueKey<InventoryRecord> INVENTORY_NAME_KEY = Internal.createUniqueKey(Inventory.INVENTORY, DSL.name("inventory_name_key"), new TableField[] { Inventory.INVENTORY.NAME }, true);
    public static final UniqueKey<InventoryRecord> INVENTORY_PKEY = Internal.createUniqueKey(Inventory.INVENTORY, DSL.name("inventory_pkey"), new TableField[] { Inventory.INVENTORY.ID }, true);
    public static final UniqueKey<OnlineChatNodeServerRecord> ONLINE_CHAT_NODE_SERVER_IPV6_IPV4_PORT_KEY = Internal.createUniqueKey(OnlineChatNodeServer.ONLINE_CHAT_NODE_SERVER, DSL.name("online_chat_node_server_ipv6_ipv4_port_key"), new TableField[] { OnlineChatNodeServer.ONLINE_CHAT_NODE_SERVER.IPV6, OnlineChatNodeServer.ONLINE_CHAT_NODE_SERVER.IPV4, OnlineChatNodeServer.ONLINE_CHAT_NODE_SERVER.PORT }, true);
    public static final UniqueKey<OnlineChatNodeServerRecord> ONLINE_CHAT_NODE_SERVER_PKEY = Internal.createUniqueKey(OnlineChatNodeServer.ONLINE_CHAT_NODE_SERVER, DSL.name("online_chat_node_server_pkey"), new TableField[] { OnlineChatNodeServer.ONLINE_CHAT_NODE_SERVER.SERVER_ID }, true);
    public static final UniqueKey<OnlineGameNodeServerRecord> ONLINE_GAME_NODE_SERVER_IPV6_IPV4_PORT_KEY = Internal.createUniqueKey(OnlineGameNodeServer.ONLINE_GAME_NODE_SERVER, DSL.name("online_game_node_server_ipv6_ipv4_port_key"), new TableField[] { OnlineGameNodeServer.ONLINE_GAME_NODE_SERVER.IPV6, OnlineGameNodeServer.ONLINE_GAME_NODE_SERVER.IPV4, OnlineGameNodeServer.ONLINE_GAME_NODE_SERVER.PORT }, true);
    public static final UniqueKey<OnlineGameNodeServerRecord> ONLINE_GAME_NODE_SERVER_PKEY = Internal.createUniqueKey(OnlineGameNodeServer.ONLINE_GAME_NODE_SERVER, DSL.name("online_game_node_server_pkey"), new TableField[] { OnlineGameNodeServer.ONLINE_GAME_NODE_SERVER.SERVER_ID }, true);
    public static final UniqueKey<OwnedItemRecord> OWNED_ITEM_PKEY = Internal.createUniqueKey(OwnedItem.OWNED_ITEM, DSL.name("owned_item_pkey"), new TableField[] { OwnedItem.OWNED_ITEM.ITEM_ID }, true);
    public static final UniqueKey<PokemonRecord> POKEMON_PKEY = Internal.createUniqueKey(Pokemon.POKEMON, DSL.name("pokemon_pkey"), new TableField[] { Pokemon.POKEMON.ID }, true);
    public static final UniqueKey<PokemonDexRecord> POKEMON_DEX_PKEY = Internal.createUniqueKey(PokemonDex.POKEMON_DEX, DSL.name("pokemon_dex_pkey"), new TableField[] { PokemonDex.POKEMON_DEX.PLAYER_ID }, true);
    public static final UniqueKey<ServerTokenRecord> SERVER_TOKEN_PKEY = Internal.createUniqueKey(ServerToken.SERVER_TOKEN, DSL.name("server_token_pkey"), new TableField[] { ServerToken.SERVER_TOKEN.ID }, true);
    public static final UniqueKey<ServerTokenRecord> SERVER_TOKEN_TOKEN_NODE_TYPE_NODE_ID_TOKEN_TYPE_KEY = Internal.createUniqueKey(ServerToken.SERVER_TOKEN, DSL.name("server_token_token_node_type_node_id_token_type_key"), new TableField[] { ServerToken.SERVER_TOKEN.TOKEN, ServerToken.SERVER_TOKEN.NODE_TYPE, ServerToken.SERVER_TOKEN.NODE_ID, ServerToken.SERVER_TOKEN.TOKEN_TYPE }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AccountContextRecord, AccountRecord> ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_ACCOUNT_ID_FKEY = Internal.createForeignKey(AccountContext.ACCOUNT_CONTEXT, DSL.name("account_context_account_id_fkey"), new TableField[] { AccountContext.ACCOUNT_CONTEXT.ACCOUNT_ID }, Keys.ACCOUNT_PKEY, new TableField[] { Account.ACCOUNT.ACCOUNT_ID }, true);
    public static final ForeignKey<AccountContextRecord, GameNodeRecord> ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_GAME_NODE_ID_FKEY = Internal.createForeignKey(AccountContext.ACCOUNT_CONTEXT, DSL.name("account_context_game_node_id_fkey"), new TableField[] { AccountContext.ACCOUNT_CONTEXT.GAME_NODE_ID }, Keys.GAME_NODE_PKEY, new TableField[] { GameNode.GAME_NODE.NODE_ID }, true);
    public static final ForeignKey<AccountContextRecord, GameNodeRecord> ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_NODE_NAME_FKEY = Internal.createForeignKey(AccountContext.ACCOUNT_CONTEXT, DSL.name("account_context_node_name_fkey"), new TableField[] { AccountContext.ACCOUNT_CONTEXT.NODE_NAME }, Keys.GAME_NODE_NODE_NAME_KEY, new TableField[] { GameNode.GAME_NODE.NODE_NAME }, true);
    public static final ForeignKey<AccountContextRecord, OnlineGameNodeServerRecord> ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_SERVER_ID_FKEY = Internal.createForeignKey(AccountContext.ACCOUNT_CONTEXT, DSL.name("account_context_server_id_fkey"), new TableField[] { AccountContext.ACCOUNT_CONTEXT.SERVER_ID }, Keys.ONLINE_GAME_NODE_SERVER_PKEY, new TableField[] { OnlineGameNodeServer.ONLINE_GAME_NODE_SERVER.SERVER_ID }, true);
    public static final ForeignKey<BlackListRecord, CharacterRecord> BLACK_LIST__BLACK_LIST_PLAYER_ID_FKEY = Internal.createForeignKey(BlackList.BLACK_LIST, DSL.name("black_list_player_id_fkey"), new TableField[] { BlackList.BLACK_LIST.PLAYER_ID }, Keys.CHARACTER_PKEY, new TableField[] { Character.CHARACTER.ID }, true);
    public static final ForeignKey<FriendListRecord, CharacterRecord> FRIEND_LIST__FRIEND_LIST_PLAYER_ID_FKEY = Internal.createForeignKey(FriendList.FRIEND_LIST, DSL.name("friend_list_player_id_fkey"), new TableField[] { FriendList.FRIEND_LIST.PLAYER_ID }, Keys.CHARACTER_PKEY, new TableField[] { Character.CHARACTER.ID }, true);
    public static final ForeignKey<OnlineChatNodeServerRecord, GameNodeRecord> ONLINE_CHAT_NODE_SERVER__ONLINE_CHAT_NODE_SERVER_NODE_ID_FKEY = Internal.createForeignKey(OnlineChatNodeServer.ONLINE_CHAT_NODE_SERVER, DSL.name("online_chat_node_server_node_id_fkey"), new TableField[] { OnlineChatNodeServer.ONLINE_CHAT_NODE_SERVER.NODE_ID }, Keys.GAME_NODE_PKEY, new TableField[] { GameNode.GAME_NODE.NODE_ID }, true);
    public static final ForeignKey<OnlineGameNodeServerRecord, GameNodeRecord> ONLINE_GAME_NODE_SERVER__ONLINE_GAME_NODE_SERVER_NODE_ID_FKEY = Internal.createForeignKey(OnlineGameNodeServer.ONLINE_GAME_NODE_SERVER, DSL.name("online_game_node_server_node_id_fkey"), new TableField[] { OnlineGameNodeServer.ONLINE_GAME_NODE_SERVER.NODE_ID }, Keys.GAME_NODE_PKEY, new TableField[] { GameNode.GAME_NODE.NODE_ID }, true);
    public static final ForeignKey<OwnedItemRecord, InventoryRecord> OWNED_ITEM__OWNED_ITEM_INVENTORY_ID_FKEY = Internal.createForeignKey(OwnedItem.OWNED_ITEM, DSL.name("owned_item_inventory_id_fkey"), new TableField[] { OwnedItem.OWNED_ITEM.INVENTORY_ID }, Keys.INVENTORY_PKEY, new TableField[] { Inventory.INVENTORY.ID }, true);
    public static final ForeignKey<PokemonDexRecord, CharacterRecord> POKEMON_DEX__POKEMON_DEX_PLAYER_ID_FKEY = Internal.createForeignKey(PokemonDex.POKEMON_DEX, DSL.name("pokemon_dex_player_id_fkey"), new TableField[] { PokemonDex.POKEMON_DEX.PLAYER_ID }, Keys.CHARACTER_PKEY, new TableField[] { Character.CHARACTER.ID }, true);
    public static final ForeignKey<ServerTokenRecord, AccountRecord> SERVER_TOKEN__SERVER_TOKEN_ACCOUNT_ID_FKEY = Internal.createForeignKey(ServerToken.SERVER_TOKEN, DSL.name("server_token_account_id_fkey"), new TableField[] { ServerToken.SERVER_TOKEN.ACCOUNT_ID }, Keys.ACCOUNT_PKEY, new TableField[] { Account.ACCOUNT.ACCOUNT_ID }, true);
}
