/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.pokemmo.db.jooq.tables.Account;
import org.pokemmo.db.jooq.tables.AccountContext;
import org.pokemmo.db.jooq.tables.BlackList;
import org.pokemmo.db.jooq.tables.Character;
import org.pokemmo.db.jooq.tables.Container;
import org.pokemmo.db.jooq.tables.FriendList;
import org.pokemmo.db.jooq.tables.GameNode;
import org.pokemmo.db.jooq.tables.Inventory;
import org.pokemmo.db.jooq.tables.OnlineChatNodeServer;
import org.pokemmo.db.jooq.tables.OnlineGameNodeServer;
import org.pokemmo.db.jooq.tables.OwnedItem;
import org.pokemmo.db.jooq.tables.PgpArmorHeaders;
import org.pokemmo.db.jooq.tables.Pokemon;
import org.pokemmo.db.jooq.tables.PokemonDex;
import org.pokemmo.db.jooq.tables.ServerToken;
import org.pokemmo.db.jooq.tables.records.PgpArmorHeadersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.account_context</code>.
     */
    public final AccountContext ACCOUNT_CONTEXT = AccountContext.ACCOUNT_CONTEXT;

    /**
     * The table <code>public.black_list</code>.
     */
    public final BlackList BLACK_LIST = BlackList.BLACK_LIST;

    /**
     * The table <code>public.character</code>.
     */
    public final Character CHARACTER = Character.CHARACTER;

    /**
     * The table <code>public.container</code>.
     */
    public final Container CONTAINER = Container.CONTAINER;

    /**
     * The table <code>public.friend_list</code>.
     */
    public final FriendList FRIEND_LIST = FriendList.FRIEND_LIST;

    /**
     * The table <code>public.game_node</code>.
     */
    public final GameNode GAME_NODE = GameNode.GAME_NODE;

    /**
     * The table <code>public.inventory</code>.
     */
    public final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>public.online_chat_node_server</code>.
     */
    public final OnlineChatNodeServer ONLINE_CHAT_NODE_SERVER = OnlineChatNodeServer.ONLINE_CHAT_NODE_SERVER;

    /**
     * The table <code>public.online_game_node_server</code>.
     */
    public final OnlineGameNodeServer ONLINE_GAME_NODE_SERVER = OnlineGameNodeServer.ONLINE_GAME_NODE_SERVER;

    /**
     * The table <code>public.owned_item</code>.
     */
    public final OwnedItem OWNED_ITEM = OwnedItem.OWNED_ITEM;

    /**
     * The table <code>public.pgp_armor_headers</code>.
     */
    public final PgpArmorHeaders PGP_ARMOR_HEADERS = PgpArmorHeaders.PGP_ARMOR_HEADERS;

    /**
     * Call <code>public.pgp_armor_headers</code>.
     */
    public static Result<PgpArmorHeadersRecord> PGP_ARMOR_HEADERS(
          Configuration configuration
        , String __1
    ) {
        return configuration.dsl().selectFrom(org.pokemmo.db.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        )).fetch();
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          String __1
    ) {
        return org.pokemmo.db.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          Field<String> __1
    ) {
        return org.pokemmo.db.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * The table <code>public.pokemon</code>.
     */
    public final Pokemon POKEMON = Pokemon.POKEMON;

    /**
     * The table <code>public.pokemon_dex</code>.
     */
    public final PokemonDex POKEMON_DEX = PokemonDex.POKEMON_DEX;

    /**
     * The table <code>public.server_token</code>.
     */
    public final ServerToken SERVER_TOKEN = ServerToken.SERVER_TOKEN;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Account.ACCOUNT,
            AccountContext.ACCOUNT_CONTEXT,
            BlackList.BLACK_LIST,
            Character.CHARACTER,
            Container.CONTAINER,
            FriendList.FRIEND_LIST,
            GameNode.GAME_NODE,
            Inventory.INVENTORY,
            OnlineChatNodeServer.ONLINE_CHAT_NODE_SERVER,
            OnlineGameNodeServer.ONLINE_GAME_NODE_SERVER,
            OwnedItem.OWNED_ITEM,
            PgpArmorHeaders.PGP_ARMOR_HEADERS,
            Pokemon.POKEMON,
            PokemonDex.POKEMON_DEX,
            ServerToken.SERVER_TOKEN
        );
    }
}
