package org.pokemmo.gameserver.game.string;

public enum FormatStringType {
    ONE_SHORT_ITEM_INDEX_ID_FORMAT(0),
    ONE_SHORT_POKEMON_INDEX_ID_FORMAT(1),
    ONE_SHORT_MOVE_INDEX_ID_FORMAT(2),
    ONE_SHORT_FORMAT(3),
    ONE_SHORT_BADGE_INDEX_ID_FORMAT(4),
    EXPORT_STRING_FORMAT(5),
    ONE_SHORT_MAP_NAME_HASH_FORMAT(6),
    ONE_SHORT_POKEMON_TYPE_INDEX_FORMAT(7),
    ONE_SHORT_GAME_CHAT_TYPE_FORMAT(8),
    INT_STRING_FORMAT(9),
    INT_TIME_DURATION_FORMAT(10),
    ONE_SHORT_POKEMON_ABILITY_INDEX_ID_FORMAT(11),
    ONE_SHORT_POKEMON_FLAVOR_TYPE_FORMAT(12),
    ONE_SHORT_SECRET_POWER_FURNITURE_INDEX_ID_FORMAT(13),
    ONE_SHORT_POKEMON_CUBE_TYPE_FORMAT(14),
    ONE_SHORT_TRAINER_NAME_INDEX_ID_FORMAT(15),
    ONE_SHORT_TRAINER_INDEX_ID_FORMAT(16),
    INT_NUMBER_FORMAT(17),
    REFERENCES_STRING_FORMAT(18),
    TWO_SHORT_GAME_BASIC_STRING_FORMAT(19),
    ONE_SHORT_NPC_NAME_FORMAT(20),
    ONE_SHORT_POKEMON_TYPE_VALUE_FORMAT(21),
    ONE_SHORT_ITEM_MOVE_LOCAL_STRING_FORMAT(22),
    ONE_SHORT_1x_FORMAT(23),//"1x "格式通配
    TWO_SHORT_ITEM_INDEX_ID_WITH_AMOUNT_FORMAT(24),
    ONE_SHORT_ITEM_STRING_OFFSET_BY_ITEM_INDEX_ID_FORMAT(25),
    ONE_OR_TWO_SHORT_NDS_ROM_TEXT_FORMAT(26),
    ONE_SHORT_ITEM_STRING_OFFSET_BY_ITEM_TYPE_FORMAT(27),
    ONE_SHORT_STRING_TYPE_NAME_BY_REGION_INDEX_ID_FORMAT(28),
    ONE_SHORT_POKEMON_CONTAINER_TYPE_FORMAT(29),
    LONG_NUMBER_FORMAT(30),
    ONE_SHORT_SMOGON_VALUE_FORMAT(31);//对战条款通配
    private byte type;
    FormatStringType(int type) {
        this.type = (byte) type;
    }
}
