/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.pokemmo.db.jooq.Keys;
import org.pokemmo.db.jooq.Public;
import org.pokemmo.db.jooq.tables.Account.AccountPath;
import org.pokemmo.db.jooq.tables.GameNode.GameNodePath;
import org.pokemmo.db.jooq.tables.OnlineGameNodeServer.OnlineGameNodeServerPath;
import org.pokemmo.db.jooq.tables.records.AccountContextRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountContext extends TableImpl<AccountContextRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.account_context</code>
     */
    public static final AccountContext ACCOUNT_CONTEXT = new AccountContext();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountContextRecord> getRecordType() {
        return AccountContextRecord.class;
    }

    /**
     * The column <code>public.account_context.account_id</code>.
     */
    public final TableField<AccountContextRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.account_context.character_id</code>.
     */
    public final TableField<AccountContextRecord, Long> CHARACTER_ID = createField(DSL.name("character_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.account_context.game_node_id</code>.
     */
    public final TableField<AccountContextRecord, Short> GAME_NODE_ID = createField(DSL.name("game_node_id"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.account_context.node_name</code>.
     */
    public final TableField<AccountContextRecord, String> NODE_NAME = createField(DSL.name("node_name"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.account_context.server_id</code>.
     */
    public final TableField<AccountContextRecord, Short> SERVER_ID = createField(DSL.name("server_id"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.account_context.is_log_out</code>.
     */
    public final TableField<AccountContextRecord, Boolean> IS_LOG_OUT = createField(DSL.name("is_log_out"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.account_context.update_at</code>.
     */
    public final TableField<AccountContextRecord, LocalDateTime> UPDATE_AT = createField(DSL.name("update_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private AccountContext(Name alias, Table<AccountContextRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AccountContext(Name alias, Table<AccountContextRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.account_context</code> table reference
     */
    public AccountContext(String alias) {
        this(DSL.name(alias), ACCOUNT_CONTEXT);
    }

    /**
     * Create an aliased <code>public.account_context</code> table reference
     */
    public AccountContext(Name alias) {
        this(alias, ACCOUNT_CONTEXT);
    }

    /**
     * Create a <code>public.account_context</code> table reference
     */
    public AccountContext() {
        this(DSL.name("account_context"), null);
    }

    public <O extends Record> AccountContext(Table<O> path, ForeignKey<O, AccountContextRecord> childPath, InverseForeignKey<O, AccountContextRecord> parentPath) {
        super(path, childPath, parentPath, ACCOUNT_CONTEXT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AccountContextPath extends AccountContext implements Path<AccountContextRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AccountContextPath(Table<O> path, ForeignKey<O, AccountContextRecord> childPath, InverseForeignKey<O, AccountContextRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AccountContextPath(Name alias, Table<AccountContextRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AccountContextPath as(String alias) {
            return new AccountContextPath(DSL.name(alias), this);
        }

        @Override
        public AccountContextPath as(Name alias) {
            return new AccountContextPath(alias, this);
        }

        @Override
        public AccountContextPath as(Table<?> alias) {
            return new AccountContextPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AccountContextRecord> getPrimaryKey() {
        return Keys.ACCOUNT_CONTEXT_PKEY;
    }

    @Override
    public List<ForeignKey<AccountContextRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_ACCOUNT_ID_FKEY, Keys.ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_GAME_NODE_ID_FKEY, Keys.ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_NODE_NAME_FKEY, Keys.ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_SERVER_ID_FKEY);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_ACCOUNT_ID_FKEY, null);

        return _account;
    }

    private transient GameNodePath _accountContextGameNodeIdFkey;

    /**
     * Get the implicit join path to the <code>public.game_node</code> table,
     * via the <code>account_context_game_node_id_fkey</code> key.
     */
    public GameNodePath accountContextGameNodeIdFkey() {
        if (_accountContextGameNodeIdFkey == null)
            _accountContextGameNodeIdFkey = new GameNodePath(this, Keys.ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_GAME_NODE_ID_FKEY, null);

        return _accountContextGameNodeIdFkey;
    }

    private transient GameNodePath _accountContextNodeNameFkey;

    /**
     * Get the implicit join path to the <code>public.game_node</code> table,
     * via the <code>account_context_node_name_fkey</code> key.
     */
    public GameNodePath accountContextNodeNameFkey() {
        if (_accountContextNodeNameFkey == null)
            _accountContextNodeNameFkey = new GameNodePath(this, Keys.ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_NODE_NAME_FKEY, null);

        return _accountContextNodeNameFkey;
    }

    private transient OnlineGameNodeServerPath _onlineGameNodeServer;

    /**
     * Get the implicit join path to the
     * <code>public.online_game_node_server</code> table.
     */
    public OnlineGameNodeServerPath onlineGameNodeServer() {
        if (_onlineGameNodeServer == null)
            _onlineGameNodeServer = new OnlineGameNodeServerPath(this, Keys.ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_SERVER_ID_FKEY, null);

        return _onlineGameNodeServer;
    }

    @Override
    public AccountContext as(String alias) {
        return new AccountContext(DSL.name(alias), this);
    }

    @Override
    public AccountContext as(Name alias) {
        return new AccountContext(alias, this);
    }

    @Override
    public AccountContext as(Table<?> alias) {
        return new AccountContext(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountContext rename(String name) {
        return new AccountContext(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountContext rename(Name name) {
        return new AccountContext(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountContext rename(Table<?> name) {
        return new AccountContext(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountContext where(Condition condition) {
        return new AccountContext(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountContext where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountContext where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountContext where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountContext where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountContext where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountContext where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountContext where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountContext whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountContext whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
