/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.pokemmo.db.jooq.Keys;
import org.pokemmo.db.jooq.Public;
import org.pokemmo.db.jooq.tables.Character.CharacterPath;
import org.pokemmo.db.jooq.tables.records.BlackListRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlackList extends TableImpl<BlackListRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.black_list</code>
     */
    public static final BlackList BLACK_LIST = new BlackList();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BlackListRecord> getRecordType() {
        return BlackListRecord.class;
    }

    /**
     * The column <code>public.black_list.player_id</code>.
     */
    public final TableField<BlackListRecord, Long> PLAYER_ID = createField(DSL.name("player_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.black_list.block_player_id</code>.
     */
    public final TableField<BlackListRecord, Long> BLOCK_PLAYER_ID = createField(DSL.name("block_player_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.black_list.block_time</code>.
     */
    public final TableField<BlackListRecord, LocalDateTime> BLOCK_TIME = createField(DSL.name("block_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.black_list.block_player_name</code>.
     */
    public final TableField<BlackListRecord, String> BLOCK_PLAYER_NAME = createField(DSL.name("block_player_name"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>public.black_list.block_reason</code>.
     */
    public final TableField<BlackListRecord, String> BLOCK_REASON = createField(DSL.name("block_reason"), SQLDataType.VARCHAR(10), this, "");

    private BlackList(Name alias, Table<BlackListRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BlackList(Name alias, Table<BlackListRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.black_list</code> table reference
     */
    public BlackList(String alias) {
        this(DSL.name(alias), BLACK_LIST);
    }

    /**
     * Create an aliased <code>public.black_list</code> table reference
     */
    public BlackList(Name alias) {
        this(alias, BLACK_LIST);
    }

    /**
     * Create a <code>public.black_list</code> table reference
     */
    public BlackList() {
        this(DSL.name("black_list"), null);
    }

    public <O extends Record> BlackList(Table<O> path, ForeignKey<O, BlackListRecord> childPath, InverseForeignKey<O, BlackListRecord> parentPath) {
        super(path, childPath, parentPath, BLACK_LIST);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BlackListPath extends BlackList implements Path<BlackListRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BlackListPath(Table<O> path, ForeignKey<O, BlackListRecord> childPath, InverseForeignKey<O, BlackListRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BlackListPath(Name alias, Table<BlackListRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BlackListPath as(String alias) {
            return new BlackListPath(DSL.name(alias), this);
        }

        @Override
        public BlackListPath as(Name alias) {
            return new BlackListPath(alias, this);
        }

        @Override
        public BlackListPath as(Table<?> alias) {
            return new BlackListPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<BlackListRecord> getPrimaryKey() {
        return Keys.BLACK_LIST_PKEY;
    }

    @Override
    public List<ForeignKey<BlackListRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BLACK_LIST__BLACK_LIST_PLAYER_ID_FKEY);
    }

    private transient CharacterPath _character;

    /**
     * Get the implicit join path to the <code>public.character</code> table.
     */
    public CharacterPath character() {
        if (_character == null)
            _character = new CharacterPath(this, Keys.BLACK_LIST__BLACK_LIST_PLAYER_ID_FKEY, null);

        return _character;
    }

    @Override
    public BlackList as(String alias) {
        return new BlackList(DSL.name(alias), this);
    }

    @Override
    public BlackList as(Name alias) {
        return new BlackList(alias, this);
    }

    @Override
    public BlackList as(Table<?> alias) {
        return new BlackList(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BlackList rename(String name) {
        return new BlackList(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BlackList rename(Name name) {
        return new BlackList(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BlackList rename(Table<?> name) {
        return new BlackList(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BlackList where(Condition condition) {
        return new BlackList(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BlackList where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BlackList where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BlackList where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BlackList where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BlackList where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BlackList where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BlackList where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BlackList whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BlackList whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
