/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.pokemmo.db.jooq.Keys;
import org.pokemmo.db.jooq.Public;
import org.pokemmo.db.jooq.tables.BlackList.BlackListPath;
import org.pokemmo.db.jooq.tables.FriendList.FriendListPath;
import org.pokemmo.db.jooq.tables.PokemonDex.PokemonDexPath;
import org.pokemmo.db.jooq.tables.records.CharacterRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Character extends TableImpl<CharacterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.character</code>
     */
    public static final Character CHARACTER = new Character();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CharacterRecord> getRecordType() {
        return CharacterRecord.class;
    }

    /**
     * The column <code>public.character.id</code>.
     */
    public final TableField<CharacterRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.character.account_id</code>.
     */
    public final TableField<CharacterRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.character.name</code>.
     */
    public final TableField<CharacterRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.character.union_name</code>.
     */
    public final TableField<CharacterRecord, String> UNION_NAME = createField(DSL.name("union_name"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.character.sex</code>.
     */
    public final TableField<CharacterRecord, Short> SEX = createField(DSL.name("sex"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.login_time_stamp</code>.
     */
    public final TableField<CharacterRecord, LocalDateTime> LOGIN_TIME_STAMP = createField(DSL.name("login_time_stamp"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.character.last_login_mac</code>.
     */
    public final TableField<CharacterRecord, Long> LAST_LOGIN_MAC = createField(DSL.name("last_login_mac"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.character.created_at</code>.
     */
    public final TableField<CharacterRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.character.online_minutes</code>.
     */
    public final TableField<CharacterRecord, Integer> ONLINE_MINUTES = createField(DSL.name("online_minutes"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.character.money</code>.
     */
    public final TableField<CharacterRecord, Integer> MONEY = createField(DSL.name("money"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.character.coins</code>.
     */
    public final TableField<CharacterRecord, Short> COINS = createField(DSL.name("coins"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.battle_points</code>.
     */
    public final TableField<CharacterRecord, Short> BATTLE_POINTS = createField(DSL.name("battle_points"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.safari_steps</code>.
     */
    public final TableField<CharacterRecord, Short> SAFARI_STEPS = createField(DSL.name("safari_steps"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.safari_ball_amount</code>.
     */
    public final TableField<CharacterRecord, Short> SAFARI_BALL_AMOUNT = createField(DSL.name("safari_ball_amount"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.other_settings_value</code>.
     */
    public final TableField<CharacterRecord, Short> OTHER_SETTINGS_VALUE = createField(DSL.name("other_settings_value"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.pc_box_expansion_number</code>.
     */
    public final TableField<CharacterRecord, Short> PC_BOX_EXPANSION_NUMBER = createField(DSL.name("pc_box_expansion_number"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.battle_box_expansion_number</code>.
     */
    public final TableField<CharacterRecord, Short> BATTLE_BOX_EXPANSION_NUMBER = createField(DSL.name("battle_box_expansion_number"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.template_amount</code>.
     */
    public final TableField<CharacterRecord, Short> TEMPLATE_AMOUNT = createField(DSL.name("template_amount"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.repel_steps</code>.
     */
    public final TableField<CharacterRecord, Short> REPEL_STEPS = createField(DSL.name("repel_steps"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.repel_item_id</code>.
     */
    public final TableField<CharacterRecord, Short> REPEL_ITEM_ID = createField(DSL.name("repel_item_id"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.lure_type</code>.
     */
    public final TableField<CharacterRecord, Short> LURE_TYPE = createField(DSL.name("lure_type"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.lure_item_id</code>.
     */
    public final TableField<CharacterRecord, Short> LURE_ITEM_ID = createField(DSL.name("lure_item_id"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.lure_steps</code>.
     */
    public final TableField<CharacterRecord, Short> LURE_STEPS = createField(DSL.name("lure_steps"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.region_id</code>.
     */
    public final TableField<CharacterRecord, Short> REGION_ID = createField(DSL.name("region_id"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column
     * <code>public.character.map_header_id_or_gba_map_group_id</code>.
     */
    public final TableField<CharacterRecord, Short> MAP_HEADER_ID_OR_GBA_MAP_GROUP_ID = createField(DSL.name("map_header_id_or_gba_map_group_id"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.gba_map_id</code>.
     */
    public final TableField<CharacterRecord, Short> GBA_MAP_ID = createField(DSL.name("gba_map_id"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.x</code>.
     */
    public final TableField<CharacterRecord, Short> X = createField(DSL.name("x"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.y</code>.
     */
    public final TableField<CharacterRecord, Short> Y = createField(DSL.name("y"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.z</code>.
     */
    public final TableField<CharacterRecord, Short> Z = createField(DSL.name("z"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.toward</code>.
     */
    public final TableField<CharacterRecord, Short> TOWARD = createField(DSL.name("toward"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.transportation</code>.
     */
    public final TableField<CharacterRecord, Short> TRANSPORTATION = createField(DSL.name("transportation"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.nameplate_status</code>.
     */
    public final TableField<CharacterRecord, Short> NAMEPLATE_STATUS = createField(DSL.name("nameplate_status"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.permission</code>.
     */
    public final TableField<CharacterRecord, Short> PERMISSION = createField(DSL.name("permission"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("3"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.model_region_index_id</code>.
     */
    public final TableField<CharacterRecord, Short> MODEL_REGION_INDEX_ID = createField(DSL.name("model_region_index_id"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.model_index_id</code>.
     */
    public final TableField<CharacterRecord, Short> MODEL_INDEX_ID = createField(DSL.name("model_index_id"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.follower_pokemon_index_id</code>.
     */
    public final TableField<CharacterRecord, Short> FOLLOWER_POKEMON_INDEX_ID = createField(DSL.name("follower_pokemon_index_id"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.follower_pokemon_rarity</code>.
     */
    public final TableField<CharacterRecord, Short> FOLLOWER_POKEMON_RARITY = createField(DSL.name("follower_pokemon_rarity"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.forehead</code>.
     */
    public final TableField<CharacterRecord, Short> FOREHEAD = createField(DSL.name("forehead"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.forehead_color</code>.
     */
    public final TableField<CharacterRecord, Short> FOREHEAD_COLOR = createField(DSL.name("forehead_color"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.hat</code>.
     */
    public final TableField<CharacterRecord, Short> HAT = createField(DSL.name("hat"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.hat_color</code>.
     */
    public final TableField<CharacterRecord, Short> HAT_COLOR = createField(DSL.name("hat_color"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.hair</code>.
     */
    public final TableField<CharacterRecord, Short> HAIR = createField(DSL.name("hair"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.hair_color</code>.
     */
    public final TableField<CharacterRecord, Short> HAIR_COLOR = createField(DSL.name("hair_color"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.eyes</code>.
     */
    public final TableField<CharacterRecord, Short> EYES = createField(DSL.name("eyes"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.eyes_color</code>.
     */
    public final TableField<CharacterRecord, Short> EYES_COLOR = createField(DSL.name("eyes_color"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.facial_hair</code>.
     */
    public final TableField<CharacterRecord, Short> FACIAL_HAIR = createField(DSL.name("facial_hair"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.facial_hair_color</code>.
     */
    public final TableField<CharacterRecord, Short> FACIAL_HAIR_COLOR = createField(DSL.name("facial_hair_color"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.back</code>.
     */
    public final TableField<CharacterRecord, Short> BACK = createField(DSL.name("back"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.back_color</code>.
     */
    public final TableField<CharacterRecord, Short> BACK_COLOR = createField(DSL.name("back_color"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.top</code>.
     */
    public final TableField<CharacterRecord, Short> TOP = createField(DSL.name("top"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.top_color</code>.
     */
    public final TableField<CharacterRecord, Short> TOP_COLOR = createField(DSL.name("top_color"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.gloves</code>.
     */
    public final TableField<CharacterRecord, Short> GLOVES = createField(DSL.name("gloves"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.gloves_color</code>.
     */
    public final TableField<CharacterRecord, Short> GLOVES_COLOR = createField(DSL.name("gloves_color"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.footwear</code>.
     */
    public final TableField<CharacterRecord, Short> FOOTWEAR = createField(DSL.name("footwear"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.footwear_color</code>.
     */
    public final TableField<CharacterRecord, Short> FOOTWEAR_COLOR = createField(DSL.name("footwear_color"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.leggings</code>.
     */
    public final TableField<CharacterRecord, Short> LEGGINGS = createField(DSL.name("leggings"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.leggings_color</code>.
     */
    public final TableField<CharacterRecord, Short> LEGGINGS_COLOR = createField(DSL.name("leggings_color"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.fishing_rod</code>.
     */
    public final TableField<CharacterRecord, Short> FISHING_ROD = createField(DSL.name("fishing_rod"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.bike</code>.
     */
    public final TableField<CharacterRecord, Short> BIKE = createField(DSL.name("bike"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.champion_flag</code>.
     */
    public final TableField<CharacterRecord, Boolean[]> CHAMPION_FLAG = createField(DSL.name("champion_flag"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("'{f,f,f,f,f}'::boolean[]"), SQLDataType.BOOLEAN)).array(), this, "");

    /**
     * The column <code>public.character.running_shoe_flag</code>.
     */
    public final TableField<CharacterRecord, Boolean[]> RUNNING_SHOE_FLAG = createField(DSL.name("running_shoe_flag"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("'{f,f,f,f,f}'::boolean[]"), SQLDataType.BOOLEAN)).array(), this, "");

    /**
     * The column <code>public.character.badge_flag</code>.
     */
    public final TableField<CharacterRecord, Short[]> BADGE_FLAG = createField(DSL.name("badge_flag"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'{0,0,0,0,0}'::smallint[]"), SQLDataType.SMALLINT)).array(), this, "");

    /**
     * The column <code>public.character.story_line_flag</code>.
     */
    public final TableField<CharacterRecord, Short[]> STORY_LINE_FLAG = createField(DSL.name("story_line_flag"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'{0,0,0,0,0}'::smallint[]"), SQLDataType.SMALLINT)).array(), this, "");

    /**
     * The column <code>public.character.city_can_fly_flag</code>.
     */
    public final TableField<CharacterRecord, Long[]> CITY_CAN_FLY_FLAG = createField(DSL.name("city_can_fly_flag"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("'{0,0,0,0,0}'::bigint[]"), SQLDataType.BIGINT)).array(), this, "");

    /**
     * The column <code>public.character.instance_times</code>.
     */
    public final TableField<CharacterRecord, Short[]> INSTANCE_TIMES = createField(DSL.name("instance_times"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'{0,0,0,0,0}'::smallint[]"), SQLDataType.SMALLINT)).array(), this, "");

    /**
     * The column <code>public.character.instance_next_time</code>.
     */
    public final TableField<CharacterRecord, LocalDateTime[]> INSTANCE_NEXT_TIME = createField(DSL.name("instance_next_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("ARRAY[(now())::timestamp without time zone, (now())::timestamp without time zone, (now())::timestamp without time zone, (now())::timestamp without time zone, (now())::timestamp without time zone]"), SQLDataType.LOCALDATETIME)).array(), this, "");

    /**
     * The column <code>public.character.first_partner_status</code>.
     */
    public final TableField<CharacterRecord, Short[]> FIRST_PARTNER_STATUS = createField(DSL.name("first_partner_status"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'{3,3,3,3,3}'::smallint[]"), SQLDataType.SMALLINT)).array(), this, "");

    /**
     * The column <code>public.character.oak_lab_status</code>.
     */
    public final TableField<CharacterRecord, Short> OAK_LAB_STATUS = createField(DSL.name("oak_lab_status"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.character.oak_parcel_status</code>.
     */
    public final TableField<CharacterRecord, Short> OAK_PARCEL_STATUS = createField(DSL.name("oak_parcel_status"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("3"), SQLDataType.SMALLINT)), this, "");

    private Character(Name alias, Table<CharacterRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Character(Name alias, Table<CharacterRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.character</code> table reference
     */
    public Character(String alias) {
        this(DSL.name(alias), CHARACTER);
    }

    /**
     * Create an aliased <code>public.character</code> table reference
     */
    public Character(Name alias) {
        this(alias, CHARACTER);
    }

    /**
     * Create a <code>public.character</code> table reference
     */
    public Character() {
        this(DSL.name("character"), null);
    }

    public <O extends Record> Character(Table<O> path, ForeignKey<O, CharacterRecord> childPath, InverseForeignKey<O, CharacterRecord> parentPath) {
        super(path, childPath, parentPath, CHARACTER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CharacterPath extends Character implements Path<CharacterRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CharacterPath(Table<O> path, ForeignKey<O, CharacterRecord> childPath, InverseForeignKey<O, CharacterRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CharacterPath(Name alias, Table<CharacterRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CharacterPath as(String alias) {
            return new CharacterPath(DSL.name(alias), this);
        }

        @Override
        public CharacterPath as(Name alias) {
            return new CharacterPath(alias, this);
        }

        @Override
        public CharacterPath as(Table<?> alias) {
            return new CharacterPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CharacterRecord, Long> getIdentity() {
        return (Identity<CharacterRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CharacterRecord> getPrimaryKey() {
        return Keys.CHARACTER_PKEY;
    }

    private transient BlackListPath _blackList;

    /**
     * Get the implicit to-many join path to the <code>public.black_list</code>
     * table
     */
    public BlackListPath blackList() {
        if (_blackList == null)
            _blackList = new BlackListPath(this, null, Keys.BLACK_LIST__BLACK_LIST_PLAYER_ID_FKEY.getInverseKey());

        return _blackList;
    }

    private transient FriendListPath _friendList;

    /**
     * Get the implicit to-many join path to the <code>public.friend_list</code>
     * table
     */
    public FriendListPath friendList() {
        if (_friendList == null)
            _friendList = new FriendListPath(this, null, Keys.FRIEND_LIST__FRIEND_LIST_PLAYER_ID_FKEY.getInverseKey());

        return _friendList;
    }

    private transient PokemonDexPath _pokemonDex;

    /**
     * Get the implicit to-many join path to the <code>public.pokemon_dex</code>
     * table
     */
    public PokemonDexPath pokemonDex() {
        if (_pokemonDex == null)
            _pokemonDex = new PokemonDexPath(this, null, Keys.POKEMON_DEX__POKEMON_DEX_PLAYER_ID_FKEY.getInverseKey());

        return _pokemonDex;
    }

    @Override
    public Character as(String alias) {
        return new Character(DSL.name(alias), this);
    }

    @Override
    public Character as(Name alias) {
        return new Character(alias, this);
    }

    @Override
    public Character as(Table<?> alias) {
        return new Character(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Character rename(String name) {
        return new Character(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Character rename(Name name) {
        return new Character(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Character rename(Table<?> name) {
        return new Character(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Character where(Condition condition) {
        return new Character(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Character where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Character where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Character where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Character where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Character where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Character where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Character where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Character whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Character whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
