/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.pokemmo.db.jooq.Keys;
import org.pokemmo.db.jooq.Public;
import org.pokemmo.db.jooq.tables.Character.CharacterPath;
import org.pokemmo.db.jooq.tables.records.FriendListRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FriendList extends TableImpl<FriendListRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.friend_list</code>
     */
    public static final FriendList FRIEND_LIST = new FriendList();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FriendListRecord> getRecordType() {
        return FriendListRecord.class;
    }

    /**
     * The column <code>public.friend_list.player_id</code>.
     */
    public final TableField<FriendListRecord, Long> PLAYER_ID = createField(DSL.name("player_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.friend_list.friend_id</code>.
     */
    public final TableField<FriendListRecord, Long> FRIEND_ID = createField(DSL.name("friend_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.friend_list.add_time</code>.
     */
    public final TableField<FriendListRecord, LocalDateTime> ADD_TIME = createField(DSL.name("add_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private FriendList(Name alias, Table<FriendListRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FriendList(Name alias, Table<FriendListRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.friend_list</code> table reference
     */
    public FriendList(String alias) {
        this(DSL.name(alias), FRIEND_LIST);
    }

    /**
     * Create an aliased <code>public.friend_list</code> table reference
     */
    public FriendList(Name alias) {
        this(alias, FRIEND_LIST);
    }

    /**
     * Create a <code>public.friend_list</code> table reference
     */
    public FriendList() {
        this(DSL.name("friend_list"), null);
    }

    public <O extends Record> FriendList(Table<O> path, ForeignKey<O, FriendListRecord> childPath, InverseForeignKey<O, FriendListRecord> parentPath) {
        super(path, childPath, parentPath, FRIEND_LIST);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FriendListPath extends FriendList implements Path<FriendListRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FriendListPath(Table<O> path, ForeignKey<O, FriendListRecord> childPath, InverseForeignKey<O, FriendListRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FriendListPath(Name alias, Table<FriendListRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FriendListPath as(String alias) {
            return new FriendListPath(DSL.name(alias), this);
        }

        @Override
        public FriendListPath as(Name alias) {
            return new FriendListPath(alias, this);
        }

        @Override
        public FriendListPath as(Table<?> alias) {
            return new FriendListPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<FriendListRecord> getPrimaryKey() {
        return Keys.FRIEND_LIST_PKEY;
    }

    @Override
    public List<ForeignKey<FriendListRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FRIEND_LIST__FRIEND_LIST_PLAYER_ID_FKEY);
    }

    private transient CharacterPath _character;

    /**
     * Get the implicit join path to the <code>public.character</code> table.
     */
    public CharacterPath character() {
        if (_character == null)
            _character = new CharacterPath(this, Keys.FRIEND_LIST__FRIEND_LIST_PLAYER_ID_FKEY, null);

        return _character;
    }

    @Override
    public FriendList as(String alias) {
        return new FriendList(DSL.name(alias), this);
    }

    @Override
    public FriendList as(Name alias) {
        return new FriendList(alias, this);
    }

    @Override
    public FriendList as(Table<?> alias) {
        return new FriendList(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FriendList rename(String name) {
        return new FriendList(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FriendList rename(Name name) {
        return new FriendList(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FriendList rename(Table<?> name) {
        return new FriendList(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FriendList where(Condition condition) {
        return new FriendList(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FriendList where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FriendList where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FriendList where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FriendList where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FriendList where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FriendList where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FriendList where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FriendList whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FriendList whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
