/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.pokemmo.db.jooq.Keys;
import org.pokemmo.db.jooq.Public;
import org.pokemmo.db.jooq.tables.AccountContext.AccountContextPath;
import org.pokemmo.db.jooq.tables.OnlineChatNodeServer.OnlineChatNodeServerPath;
import org.pokemmo.db.jooq.tables.OnlineGameNodeServer.OnlineGameNodeServerPath;
import org.pokemmo.db.jooq.tables.records.GameNodeRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameNode extends TableImpl<GameNodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.game_node</code>
     */
    public static final GameNode GAME_NODE = new GameNode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GameNodeRecord> getRecordType() {
        return GameNodeRecord.class;
    }

    /**
     * The column <code>public.game_node.node_id</code>.
     */
    public final TableField<GameNodeRecord, Integer> NODE_ID = createField(DSL.name("node_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.game_node.node_type</code>.
     */
    public final TableField<GameNodeRecord, String> NODE_TYPE = createField(DSL.name("node_type"), SQLDataType.VARCHAR(4).nullable(false).defaultValue(DSL.field(DSL.raw("'game'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.game_node.node_name</code>.
     */
    public final TableField<GameNodeRecord, String> NODE_NAME = createField(DSL.name("node_name"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.game_node.port</code>.
     */
    public final TableField<GameNodeRecord, Integer> PORT = createField(DSL.name("port"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.game_node.permission_id</code>.
     */
    public final TableField<GameNodeRecord, Short> PERMISSION_ID = createField(DSL.name("permission_id"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.game_node.is_join_able</code>.
     */
    public final TableField<GameNodeRecord, Boolean> IS_JOIN_ABLE = createField(DSL.name("is_join_able"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.game_node.created_at</code>.
     */
    public final TableField<GameNodeRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private GameNode(Name alias, Table<GameNodeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GameNode(Name alias, Table<GameNodeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.game_node</code> table reference
     */
    public GameNode(String alias) {
        this(DSL.name(alias), GAME_NODE);
    }

    /**
     * Create an aliased <code>public.game_node</code> table reference
     */
    public GameNode(Name alias) {
        this(alias, GAME_NODE);
    }

    /**
     * Create a <code>public.game_node</code> table reference
     */
    public GameNode() {
        this(DSL.name("game_node"), null);
    }

    public <O extends Record> GameNode(Table<O> path, ForeignKey<O, GameNodeRecord> childPath, InverseForeignKey<O, GameNodeRecord> parentPath) {
        super(path, childPath, parentPath, GAME_NODE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GameNodePath extends GameNode implements Path<GameNodeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GameNodePath(Table<O> path, ForeignKey<O, GameNodeRecord> childPath, InverseForeignKey<O, GameNodeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GameNodePath(Name alias, Table<GameNodeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GameNodePath as(String alias) {
            return new GameNodePath(DSL.name(alias), this);
        }

        @Override
        public GameNodePath as(Name alias) {
            return new GameNodePath(alias, this);
        }

        @Override
        public GameNodePath as(Table<?> alias) {
            return new GameNodePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GameNodeRecord, Integer> getIdentity() {
        return (Identity<GameNodeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<GameNodeRecord> getPrimaryKey() {
        return Keys.GAME_NODE_PKEY;
    }

    @Override
    public List<UniqueKey<GameNodeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.GAME_NODE_NODE_NAME_KEY);
    }

    private transient AccountContextPath _accountContextGameNodeIdFkey;

    /**
     * Get the implicit to-many join path to the
     * <code>public.account_context</code> table, via the
     * <code>account_context_game_node_id_fkey</code> key
     */
    public AccountContextPath accountContextGameNodeIdFkey() {
        if (_accountContextGameNodeIdFkey == null)
            _accountContextGameNodeIdFkey = new AccountContextPath(this, null, Keys.ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_GAME_NODE_ID_FKEY.getInverseKey());

        return _accountContextGameNodeIdFkey;
    }

    private transient OnlineChatNodeServerPath _onlineChatNodeServer;

    /**
     * Get the implicit to-many join path to the
     * <code>public.online_chat_node_server</code> table
     */
    public OnlineChatNodeServerPath onlineChatNodeServer() {
        if (_onlineChatNodeServer == null)
            _onlineChatNodeServer = new OnlineChatNodeServerPath(this, null, Keys.ONLINE_CHAT_NODE_SERVER__ONLINE_CHAT_NODE_SERVER_NODE_ID_FKEY.getInverseKey());

        return _onlineChatNodeServer;
    }

    private transient OnlineGameNodeServerPath _onlineGameNodeServer;

    /**
     * Get the implicit to-many join path to the
     * <code>public.online_game_node_server</code> table
     */
    public OnlineGameNodeServerPath onlineGameNodeServer() {
        if (_onlineGameNodeServer == null)
            _onlineGameNodeServer = new OnlineGameNodeServerPath(this, null, Keys.ONLINE_GAME_NODE_SERVER__ONLINE_GAME_NODE_SERVER_NODE_ID_FKEY.getInverseKey());

        return _onlineGameNodeServer;
    }

    private transient AccountContextPath _accountContextNodeNameFkey;

    /**
     * Get the implicit to-many join path to the
     * <code>public.account_context</code> table, via the
     * <code>account_context_node_name_fkey</code> key
     */
    public AccountContextPath accountContextNodeNameFkey() {
        if (_accountContextNodeNameFkey == null)
            _accountContextNodeNameFkey = new AccountContextPath(this, null, Keys.ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_NODE_NAME_FKEY.getInverseKey());

        return _accountContextNodeNameFkey;
    }

    @Override
    public GameNode as(String alias) {
        return new GameNode(DSL.name(alias), this);
    }

    @Override
    public GameNode as(Name alias) {
        return new GameNode(alias, this);
    }

    @Override
    public GameNode as(Table<?> alias) {
        return new GameNode(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GameNode rename(String name) {
        return new GameNode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameNode rename(Name name) {
        return new GameNode(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameNode rename(Table<?> name) {
        return new GameNode(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameNode where(Condition condition) {
        return new GameNode(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameNode where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameNode where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameNode where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameNode where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameNode where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameNode where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameNode where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameNode whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameNode whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
