/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.postgres.extensions.bindings.InetBinding;
import org.jooq.postgres.extensions.types.Inet;
import org.pokemmo.db.jooq.Keys;
import org.pokemmo.db.jooq.Public;
import org.pokemmo.db.jooq.tables.GameNode.GameNodePath;
import org.pokemmo.db.jooq.tables.records.OnlineChatNodeServerRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OnlineChatNodeServer extends TableImpl<OnlineChatNodeServerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.online_chat_node_server</code>
     */
    public static final OnlineChatNodeServer ONLINE_CHAT_NODE_SERVER = new OnlineChatNodeServer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OnlineChatNodeServerRecord> getRecordType() {
        return OnlineChatNodeServerRecord.class;
    }

    /**
     * The column <code>public.online_chat_node_server.server_id</code>.
     */
    public final TableField<OnlineChatNodeServerRecord, Integer> SERVER_ID = createField(DSL.name("server_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.online_chat_node_server.node_id</code>.
     */
    public final TableField<OnlineChatNodeServerRecord, Integer> NODE_ID = createField(DSL.name("node_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.online_chat_node_server.ipv4</code>.
     */
    public final TableField<OnlineChatNodeServerRecord, Inet> IPV4 = createField(DSL.name("ipv4"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"inet\"").nullable(false), this, "", new InetBinding());

    /**
     * The column <code>public.online_chat_node_server.ipv6</code>.
     */
    public final TableField<OnlineChatNodeServerRecord, Inet> IPV6 = createField(DSL.name("ipv6"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"inet\"").nullable(false), this, "", new InetBinding());

    /**
     * The column <code>public.online_chat_node_server.port</code>.
     */
    public final TableField<OnlineChatNodeServerRecord, Integer> PORT = createField(DSL.name("port"), SQLDataType.INTEGER.nullable(false), this, "");

    private OnlineChatNodeServer(Name alias, Table<OnlineChatNodeServerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OnlineChatNodeServer(Name alias, Table<OnlineChatNodeServerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.online_chat_node_server</code> table
     * reference
     */
    public OnlineChatNodeServer(String alias) {
        this(DSL.name(alias), ONLINE_CHAT_NODE_SERVER);
    }

    /**
     * Create an aliased <code>public.online_chat_node_server</code> table
     * reference
     */
    public OnlineChatNodeServer(Name alias) {
        this(alias, ONLINE_CHAT_NODE_SERVER);
    }

    /**
     * Create a <code>public.online_chat_node_server</code> table reference
     */
    public OnlineChatNodeServer() {
        this(DSL.name("online_chat_node_server"), null);
    }

    public <O extends Record> OnlineChatNodeServer(Table<O> path, ForeignKey<O, OnlineChatNodeServerRecord> childPath, InverseForeignKey<O, OnlineChatNodeServerRecord> parentPath) {
        super(path, childPath, parentPath, ONLINE_CHAT_NODE_SERVER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OnlineChatNodeServerPath extends OnlineChatNodeServer implements Path<OnlineChatNodeServerRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OnlineChatNodeServerPath(Table<O> path, ForeignKey<O, OnlineChatNodeServerRecord> childPath, InverseForeignKey<O, OnlineChatNodeServerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OnlineChatNodeServerPath(Name alias, Table<OnlineChatNodeServerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OnlineChatNodeServerPath as(String alias) {
            return new OnlineChatNodeServerPath(DSL.name(alias), this);
        }

        @Override
        public OnlineChatNodeServerPath as(Name alias) {
            return new OnlineChatNodeServerPath(alias, this);
        }

        @Override
        public OnlineChatNodeServerPath as(Table<?> alias) {
            return new OnlineChatNodeServerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<OnlineChatNodeServerRecord, Integer> getIdentity() {
        return (Identity<OnlineChatNodeServerRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OnlineChatNodeServerRecord> getPrimaryKey() {
        return Keys.ONLINE_CHAT_NODE_SERVER_PKEY;
    }

    @Override
    public List<UniqueKey<OnlineChatNodeServerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ONLINE_CHAT_NODE_SERVER_IPV6_IPV4_PORT_KEY);
    }

    @Override
    public List<ForeignKey<OnlineChatNodeServerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ONLINE_CHAT_NODE_SERVER__ONLINE_CHAT_NODE_SERVER_NODE_ID_FKEY);
    }

    private transient GameNodePath _gameNode;

    /**
     * Get the implicit join path to the <code>public.game_node</code> table.
     */
    public GameNodePath gameNode() {
        if (_gameNode == null)
            _gameNode = new GameNodePath(this, Keys.ONLINE_CHAT_NODE_SERVER__ONLINE_CHAT_NODE_SERVER_NODE_ID_FKEY, null);

        return _gameNode;
    }

    @Override
    public OnlineChatNodeServer as(String alias) {
        return new OnlineChatNodeServer(DSL.name(alias), this);
    }

    @Override
    public OnlineChatNodeServer as(Name alias) {
        return new OnlineChatNodeServer(alias, this);
    }

    @Override
    public OnlineChatNodeServer as(Table<?> alias) {
        return new OnlineChatNodeServer(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OnlineChatNodeServer rename(String name) {
        return new OnlineChatNodeServer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OnlineChatNodeServer rename(Name name) {
        return new OnlineChatNodeServer(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OnlineChatNodeServer rename(Table<?> name) {
        return new OnlineChatNodeServer(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OnlineChatNodeServer where(Condition condition) {
        return new OnlineChatNodeServer(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OnlineChatNodeServer where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OnlineChatNodeServer where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OnlineChatNodeServer where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OnlineChatNodeServer where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OnlineChatNodeServer where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OnlineChatNodeServer where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OnlineChatNodeServer where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OnlineChatNodeServer whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OnlineChatNodeServer whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
