/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.postgres.extensions.bindings.InetBinding;
import org.jooq.postgres.extensions.types.Inet;
import org.pokemmo.db.jooq.Keys;
import org.pokemmo.db.jooq.Public;
import org.pokemmo.db.jooq.tables.AccountContext.AccountContextPath;
import org.pokemmo.db.jooq.tables.GameNode.GameNodePath;
import org.pokemmo.db.jooq.tables.records.OnlineGameNodeServerRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OnlineGameNodeServer extends TableImpl<OnlineGameNodeServerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.online_game_node_server</code>
     */
    public static final OnlineGameNodeServer ONLINE_GAME_NODE_SERVER = new OnlineGameNodeServer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OnlineGameNodeServerRecord> getRecordType() {
        return OnlineGameNodeServerRecord.class;
    }

    /**
     * The column <code>public.online_game_node_server.server_id</code>.
     */
    public final TableField<OnlineGameNodeServerRecord, Integer> SERVER_ID = createField(DSL.name("server_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.online_game_node_server.node_id</code>.
     */
    public final TableField<OnlineGameNodeServerRecord, Integer> NODE_ID = createField(DSL.name("node_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.online_game_node_server.ipv4</code>.
     */
    public final TableField<OnlineGameNodeServerRecord, Inet> IPV4 = createField(DSL.name("ipv4"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"inet\"").nullable(false), this, "", new InetBinding());

    /**
     * The column <code>public.online_game_node_server.ipv6</code>.
     */
    public final TableField<OnlineGameNodeServerRecord, Inet> IPV6 = createField(DSL.name("ipv6"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"inet\"").nullable(false), this, "", new InetBinding());

    /**
     * The column <code>public.online_game_node_server.port</code>.
     */
    public final TableField<OnlineGameNodeServerRecord, Integer> PORT = createField(DSL.name("port"), SQLDataType.INTEGER.nullable(false), this, "");

    private OnlineGameNodeServer(Name alias, Table<OnlineGameNodeServerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OnlineGameNodeServer(Name alias, Table<OnlineGameNodeServerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.online_game_node_server</code> table
     * reference
     */
    public OnlineGameNodeServer(String alias) {
        this(DSL.name(alias), ONLINE_GAME_NODE_SERVER);
    }

    /**
     * Create an aliased <code>public.online_game_node_server</code> table
     * reference
     */
    public OnlineGameNodeServer(Name alias) {
        this(alias, ONLINE_GAME_NODE_SERVER);
    }

    /**
     * Create a <code>public.online_game_node_server</code> table reference
     */
    public OnlineGameNodeServer() {
        this(DSL.name("online_game_node_server"), null);
    }

    public <O extends Record> OnlineGameNodeServer(Table<O> path, ForeignKey<O, OnlineGameNodeServerRecord> childPath, InverseForeignKey<O, OnlineGameNodeServerRecord> parentPath) {
        super(path, childPath, parentPath, ONLINE_GAME_NODE_SERVER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OnlineGameNodeServerPath extends OnlineGameNodeServer implements Path<OnlineGameNodeServerRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OnlineGameNodeServerPath(Table<O> path, ForeignKey<O, OnlineGameNodeServerRecord> childPath, InverseForeignKey<O, OnlineGameNodeServerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OnlineGameNodeServerPath(Name alias, Table<OnlineGameNodeServerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OnlineGameNodeServerPath as(String alias) {
            return new OnlineGameNodeServerPath(DSL.name(alias), this);
        }

        @Override
        public OnlineGameNodeServerPath as(Name alias) {
            return new OnlineGameNodeServerPath(alias, this);
        }

        @Override
        public OnlineGameNodeServerPath as(Table<?> alias) {
            return new OnlineGameNodeServerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<OnlineGameNodeServerRecord, Integer> getIdentity() {
        return (Identity<OnlineGameNodeServerRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OnlineGameNodeServerRecord> getPrimaryKey() {
        return Keys.ONLINE_GAME_NODE_SERVER_PKEY;
    }

    @Override
    public List<UniqueKey<OnlineGameNodeServerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ONLINE_GAME_NODE_SERVER_IPV6_IPV4_PORT_KEY);
    }

    @Override
    public List<ForeignKey<OnlineGameNodeServerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ONLINE_GAME_NODE_SERVER__ONLINE_GAME_NODE_SERVER_NODE_ID_FKEY);
    }

    private transient GameNodePath _gameNode;

    /**
     * Get the implicit join path to the <code>public.game_node</code> table.
     */
    public GameNodePath gameNode() {
        if (_gameNode == null)
            _gameNode = new GameNodePath(this, Keys.ONLINE_GAME_NODE_SERVER__ONLINE_GAME_NODE_SERVER_NODE_ID_FKEY, null);

        return _gameNode;
    }

    private transient AccountContextPath _accountContext;

    /**
     * Get the implicit to-many join path to the
     * <code>public.account_context</code> table
     */
    public AccountContextPath accountContext() {
        if (_accountContext == null)
            _accountContext = new AccountContextPath(this, null, Keys.ACCOUNT_CONTEXT__ACCOUNT_CONTEXT_SERVER_ID_FKEY.getInverseKey());

        return _accountContext;
    }

    @Override
    public OnlineGameNodeServer as(String alias) {
        return new OnlineGameNodeServer(DSL.name(alias), this);
    }

    @Override
    public OnlineGameNodeServer as(Name alias) {
        return new OnlineGameNodeServer(alias, this);
    }

    @Override
    public OnlineGameNodeServer as(Table<?> alias) {
        return new OnlineGameNodeServer(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OnlineGameNodeServer rename(String name) {
        return new OnlineGameNodeServer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OnlineGameNodeServer rename(Name name) {
        return new OnlineGameNodeServer(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OnlineGameNodeServer rename(Table<?> name) {
        return new OnlineGameNodeServer(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OnlineGameNodeServer where(Condition condition) {
        return new OnlineGameNodeServer(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OnlineGameNodeServer where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OnlineGameNodeServer where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OnlineGameNodeServer where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OnlineGameNodeServer where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OnlineGameNodeServer where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OnlineGameNodeServer where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OnlineGameNodeServer where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OnlineGameNodeServer whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OnlineGameNodeServer whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
