/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.pokemmo.db.jooq.Keys;
import org.pokemmo.db.jooq.Public;
import org.pokemmo.db.jooq.tables.Inventory.InventoryPath;
import org.pokemmo.db.jooq.tables.records.OwnedItemRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OwnedItem extends TableImpl<OwnedItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.owned_item</code>
     */
    public static final OwnedItem OWNED_ITEM = new OwnedItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OwnedItemRecord> getRecordType() {
        return OwnedItemRecord.class;
    }

    /**
     * The column <code>public.owned_item.item_id</code>.
     */
    public final TableField<OwnedItemRecord, Long> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.owned_item.owner_id</code>.
     */
    public final TableField<OwnedItemRecord, Long> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.owned_item.item_index_id</code>.
     */
    public final TableField<OwnedItemRecord, Short> ITEM_INDEX_ID = createField(DSL.name("item_index_id"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.owned_item.item_amount</code>.
     */
    public final TableField<OwnedItemRecord, Short> ITEM_AMOUNT = createField(DSL.name("item_amount"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.owned_item.inventory_id</code>.
     */
    public final TableField<OwnedItemRecord, Short> INVENTORY_ID = createField(DSL.name("inventory_id"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.owned_item.color_id</code>.
     */
    public final TableField<OwnedItemRecord, Short> COLOR_ID = createField(DSL.name("color_id"), SQLDataType.SMALLINT.defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.owned_item.item_region_index_id</code>.
     */
    public final TableField<OwnedItemRecord, Short> ITEM_REGION_INDEX_ID = createField(DSL.name("item_region_index_id"), SQLDataType.SMALLINT.defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.owned_item.pvp_reward_level</code>.
     */
    public final TableField<OwnedItemRecord, Short> PVP_REWARD_LEVEL = createField(DSL.name("pvp_reward_level"), SQLDataType.SMALLINT.defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.owned_item.pvp_reward_season</code>.
     */
    public final TableField<OwnedItemRecord, Short> PVP_REWARD_SEASON = createField(DSL.name("pvp_reward_season"), SQLDataType.SMALLINT.defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.owned_item.pvp_reward_time</code>.
     */
    public final TableField<OwnedItemRecord, LocalDateTime> PVP_REWARD_TIME = createField(DSL.name("pvp_reward_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private OwnedItem(Name alias, Table<OwnedItemRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OwnedItem(Name alias, Table<OwnedItemRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.owned_item</code> table reference
     */
    public OwnedItem(String alias) {
        this(DSL.name(alias), OWNED_ITEM);
    }

    /**
     * Create an aliased <code>public.owned_item</code> table reference
     */
    public OwnedItem(Name alias) {
        this(alias, OWNED_ITEM);
    }

    /**
     * Create a <code>public.owned_item</code> table reference
     */
    public OwnedItem() {
        this(DSL.name("owned_item"), null);
    }

    public <O extends Record> OwnedItem(Table<O> path, ForeignKey<O, OwnedItemRecord> childPath, InverseForeignKey<O, OwnedItemRecord> parentPath) {
        super(path, childPath, parentPath, OWNED_ITEM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OwnedItemPath extends OwnedItem implements Path<OwnedItemRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OwnedItemPath(Table<O> path, ForeignKey<O, OwnedItemRecord> childPath, InverseForeignKey<O, OwnedItemRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OwnedItemPath(Name alias, Table<OwnedItemRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OwnedItemPath as(String alias) {
            return new OwnedItemPath(DSL.name(alias), this);
        }

        @Override
        public OwnedItemPath as(Name alias) {
            return new OwnedItemPath(alias, this);
        }

        @Override
        public OwnedItemPath as(Table<?> alias) {
            return new OwnedItemPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OwnedItemRecord> getPrimaryKey() {
        return Keys.OWNED_ITEM_PKEY;
    }

    @Override
    public List<ForeignKey<OwnedItemRecord, ?>> getReferences() {
        return Arrays.asList(Keys.OWNED_ITEM__OWNED_ITEM_INVENTORY_ID_FKEY);
    }

    private transient InventoryPath _inventory;

    /**
     * Get the implicit join path to the <code>public.inventory</code> table.
     */
    public InventoryPath inventory() {
        if (_inventory == null)
            _inventory = new InventoryPath(this, Keys.OWNED_ITEM__OWNED_ITEM_INVENTORY_ID_FKEY, null);

        return _inventory;
    }

    @Override
    public OwnedItem as(String alias) {
        return new OwnedItem(DSL.name(alias), this);
    }

    @Override
    public OwnedItem as(Name alias) {
        return new OwnedItem(alias, this);
    }

    @Override
    public OwnedItem as(Table<?> alias) {
        return new OwnedItem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OwnedItem rename(String name) {
        return new OwnedItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OwnedItem rename(Name name) {
        return new OwnedItem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OwnedItem rename(Table<?> name) {
        return new OwnedItem(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OwnedItem where(Condition condition) {
        return new OwnedItem(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OwnedItem where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OwnedItem where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OwnedItem where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OwnedItem where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OwnedItem where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OwnedItem where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OwnedItem where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OwnedItem whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OwnedItem whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
