/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.pokemmo.db.jooq.Keys;
import org.pokemmo.db.jooq.Public;
import org.pokemmo.db.jooq.tables.Character.CharacterPath;
import org.pokemmo.db.jooq.tables.records.PokemonDexRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PokemonDex extends TableImpl<PokemonDexRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pokemon_dex</code>
     */
    public static final PokemonDex POKEMON_DEX = new PokemonDex();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PokemonDexRecord> getRecordType() {
        return PokemonDexRecord.class;
    }

    /**
     * The column <code>public.pokemon_dex.player_id</code>.
     */
    public final TableField<PokemonDexRecord, Long> PLAYER_ID = createField(DSL.name("player_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.pokemon_dex.meet_level</code>.
     */
    public final TableField<PokemonDexRecord, byte[]> MEET_LEVEL = createField(DSL.name("meet_level"), SQLDataType.BLOB.nullable(false).defaultValue(DSL.field(DSL.raw("decode(repeat('00'::text, 81), 'hex'::text)"), SQLDataType.BLOB)), this, "");

    /**
     * The column <code>public.pokemon_dex.already_have_level</code>.
     */
    public final TableField<PokemonDexRecord, byte[]> ALREADY_HAVE_LEVEL = createField(DSL.name("already_have_level"), SQLDataType.BLOB.nullable(false).defaultValue(DSL.field(DSL.raw("decode(repeat('00'::text, 81), 'hex'::text)"), SQLDataType.BLOB)), this, "");

    /**
     * The column <code>public.pokemon_dex.caught_level</code>.
     */
    public final TableField<PokemonDexRecord, byte[]> CAUGHT_LEVEL = createField(DSL.name("caught_level"), SQLDataType.BLOB.nullable(false).defaultValue(DSL.field(DSL.raw("decode(repeat('00'::text, 81), 'hex'::text)"), SQLDataType.BLOB)), this, "");

    /**
     * The column <code>public.pokemon_dex.caught_alpha_level</code>.
     */
    public final TableField<PokemonDexRecord, byte[]> CAUGHT_ALPHA_LEVEL = createField(DSL.name("caught_alpha_level"), SQLDataType.BLOB.nullable(false).defaultValue(DSL.field(DSL.raw("decode(repeat('00'::text, 81), 'hex'::text)"), SQLDataType.BLOB)), this, "");

    private PokemonDex(Name alias, Table<PokemonDexRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PokemonDex(Name alias, Table<PokemonDexRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.pokemon_dex</code> table reference
     */
    public PokemonDex(String alias) {
        this(DSL.name(alias), POKEMON_DEX);
    }

    /**
     * Create an aliased <code>public.pokemon_dex</code> table reference
     */
    public PokemonDex(Name alias) {
        this(alias, POKEMON_DEX);
    }

    /**
     * Create a <code>public.pokemon_dex</code> table reference
     */
    public PokemonDex() {
        this(DSL.name("pokemon_dex"), null);
    }

    public <O extends Record> PokemonDex(Table<O> path, ForeignKey<O, PokemonDexRecord> childPath, InverseForeignKey<O, PokemonDexRecord> parentPath) {
        super(path, childPath, parentPath, POKEMON_DEX);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PokemonDexPath extends PokemonDex implements Path<PokemonDexRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PokemonDexPath(Table<O> path, ForeignKey<O, PokemonDexRecord> childPath, InverseForeignKey<O, PokemonDexRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PokemonDexPath(Name alias, Table<PokemonDexRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PokemonDexPath as(String alias) {
            return new PokemonDexPath(DSL.name(alias), this);
        }

        @Override
        public PokemonDexPath as(Name alias) {
            return new PokemonDexPath(alias, this);
        }

        @Override
        public PokemonDexPath as(Table<?> alias) {
            return new PokemonDexPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PokemonDexRecord> getPrimaryKey() {
        return Keys.POKEMON_DEX_PKEY;
    }

    @Override
    public List<ForeignKey<PokemonDexRecord, ?>> getReferences() {
        return Arrays.asList(Keys.POKEMON_DEX__POKEMON_DEX_PLAYER_ID_FKEY);
    }

    private transient CharacterPath _character;

    /**
     * Get the implicit join path to the <code>public.character</code> table.
     */
    public CharacterPath character() {
        if (_character == null)
            _character = new CharacterPath(this, Keys.POKEMON_DEX__POKEMON_DEX_PLAYER_ID_FKEY, null);

        return _character;
    }

    @Override
    public PokemonDex as(String alias) {
        return new PokemonDex(DSL.name(alias), this);
    }

    @Override
    public PokemonDex as(Name alias) {
        return new PokemonDex(alias, this);
    }

    @Override
    public PokemonDex as(Table<?> alias) {
        return new PokemonDex(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PokemonDex rename(String name) {
        return new PokemonDex(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PokemonDex rename(Name name) {
        return new PokemonDex(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PokemonDex rename(Table<?> name) {
        return new PokemonDex(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PokemonDex where(Condition condition) {
        return new PokemonDex(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PokemonDex where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PokemonDex where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PokemonDex where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PokemonDex where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PokemonDex where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PokemonDex where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PokemonDex where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PokemonDex whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PokemonDex whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
