/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.pokemmo.db.jooq.Keys;
import org.pokemmo.db.jooq.Public;
import org.pokemmo.db.jooq.tables.records.PokemonRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pokemon extends TableImpl<PokemonRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pokemon</code>
     */
    public static final Pokemon POKEMON = new Pokemon();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PokemonRecord> getRecordType() {
        return PokemonRecord.class;
    }

    /**
     * The column <code>public.pokemon.id</code>.
     */
    public final TableField<PokemonRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.pokemon.trainer_id</code>.
     */
    public final TableField<PokemonRecord, Long> TRAINER_ID = createField(DSL.name("trainer_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.pokemon.widget_type</code>.
     */
    public final TableField<PokemonRecord, Short> WIDGET_TYPE = createField(DSL.name("widget_type"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.pokemon.container_id</code>.
     */
    public final TableField<PokemonRecord, Integer> CONTAINER_ID = createField(DSL.name("container_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.pokemon.container_position</code>.
     */
    public final TableField<PokemonRecord, Short> CONTAINER_POSITION = createField(DSL.name("container_position"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.pokemon.dex_id</code>.
     */
    public final TableField<PokemonRecord, Short> DEX_ID = createField(DSL.name("dex_id"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.pokemon.personality_value</code>.
     */
    public final TableField<PokemonRecord, Integer> PERSONALITY_VALUE = createField(DSL.name("personality_value"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("(((random() * (((2147483647)::bigint - ('-2147483648'::integer)::bigint))::double precision) + (('-2147483648'::integer)::bigint)::double precision))::integer"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.pokemon.original_trainer_id</code>.
     */
    public final TableField<PokemonRecord, Long> ORIGINAL_TRAINER_ID = createField(DSL.name("original_trainer_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.pokemon.ot_name</code>.
     */
    public final TableField<PokemonRecord, String> OT_NAME = createField(DSL.name("ot_name"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.pokemon.name</code>.
     */
    public final TableField<PokemonRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(32).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.pokemon.mark_status</code>.
     */
    public final TableField<PokemonRecord, Short> MARK_STATUS = createField(DSL.name("mark_status"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.pokemon.status</code>.
     */
    public final TableField<PokemonRecord, Short> STATUS = createField(DSL.name("status"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.pokemon.level_value</code>.
     */
    public final TableField<PokemonRecord, Short> LEVEL_VALUE = createField(DSL.name("level_value"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.pokemon.current_hp</code>.
     */
    public final TableField<PokemonRecord, Short> CURRENT_HP = createField(DSL.name("current_hp"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.pokemon.item</code>.
     */
    public final TableField<PokemonRecord, Short> ITEM = createField(DSL.name("item"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.pokemon.exp</code>.
     */
    public final TableField<PokemonRecord, Integer> EXP = createField(DSL.name("exp"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.pokemon.pp_up_times</code>.
     */
    public final TableField<PokemonRecord, Short> PP_UP_TIMES = createField(DSL.name("pp_up_times"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.pokemon.friend_value</code>.
     */
    public final TableField<PokemonRecord, Short> FRIEND_VALUE = createField(DSL.name("friend_value"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.pokemon.moves</code>.
     */
    public final TableField<PokemonRecord, Short[]> MOVES = createField(DSL.name("moves"), SQLDataType.SMALLINT.nullable(false).array(), this, "");

    /**
     * The column <code>public.pokemon.moves_pp</code>.
     */
    public final TableField<PokemonRecord, Short[]> MOVES_PP = createField(DSL.name("moves_pp"), SQLDataType.SMALLINT.nullable(false).array(), this, "");

    /**
     * The column <code>public.pokemon.can_remember_moves</code>.
     */
    public final TableField<PokemonRecord, Short[]> CAN_REMEMBER_MOVES = createField(DSL.name("can_remember_moves"), SQLDataType.SMALLINT.nullable(false).array(), this, "");

    /**
     * The column <code>public.pokemon.ev_values</code>.
     */
    public final TableField<PokemonRecord, Short[]> EV_VALUES = createField(DSL.name("ev_values"), SQLDataType.SMALLINT.nullable(false).array(), this, "");

    /**
     * The column <code>public.pokemon.contests_category_values</code>.
     */
    public final TableField<PokemonRecord, Short[]> CONTESTS_CATEGORY_VALUES = createField(DSL.name("contests_category_values"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("array_fill(0, ARRAY[5])"), SQLDataType.SMALLINT)).array(), this, "");

    /**
     * The column <code>public.pokemon.catch_address</code>.
     */
    public final TableField<PokemonRecord, Short> CATCH_ADDRESS = createField(DSL.name("catch_address"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.pokemon.catch_level</code>.
     */
    public final TableField<PokemonRecord, Short> CATCH_LEVEL = createField(DSL.name("catch_level"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.pokemon.catch_region</code>.
     */
    public final TableField<PokemonRecord, Short> CATCH_REGION = createField(DSL.name("catch_region"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.pokemon.ball_type</code>.
     */
    public final TableField<PokemonRecord, Short> BALL_TYPE = createField(DSL.name("ball_type"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("3"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.pokemon.form_type</code>.
     */
    public final TableField<PokemonRecord, Short> FORM_TYPE = createField(DSL.name("form_type"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.pokemon.iv_values</code>.
     */
    public final TableField<PokemonRecord, Short[]> IV_VALUES = createField(DSL.name("iv_values"), SQLDataType.SMALLINT.nullable(false).array(), this, "");

    /**
     * The column <code>public.pokemon.ability</code>.
     */
    public final TableField<PokemonRecord, Short> ABILITY = createField(DSL.name("ability"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.pokemon.contest_ribbon</code>.
     */
    public final TableField<PokemonRecord, Short[]> CONTEST_RIBBON = createField(DSL.name("contest_ribbon"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("array_fill(0, ARRAY[6])"), SQLDataType.SMALLINT)).array(), this, "");

    /**
     * The column <code>public.pokemon.normal_ribbon</code>.
     */
    public final TableField<PokemonRecord, Boolean[]> NORMAL_RIBBON = createField(DSL.name("normal_ribbon"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("array_fill(false, ARRAY[16])"), SQLDataType.BOOLEAN)).array(), this, "");

    /**
     * The column <code>public.pokemon.has_hidden_ability</code>.
     */
    public final TableField<PokemonRecord, Boolean> HAS_HIDDEN_ABILITY = createField(DSL.name("has_hidden_ability"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.pokemon.is_shiny</code>.
     */
    public final TableField<PokemonRecord, Boolean> IS_SHINY = createField(DSL.name("is_shiny"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.pokemon.is_alpha</code>.
     */
    public final TableField<PokemonRecord, Boolean> IS_ALPHA = createField(DSL.name("is_alpha"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.pokemon.is_secret</code>.
     */
    public final TableField<PokemonRecord, Boolean> IS_SECRET = createField(DSL.name("is_secret"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.pokemon.catch_time</code>.
     */
    public final TableField<PokemonRecord, LocalDateTime> CATCH_TIME = createField(DSL.name("catch_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.pokemon.egg_value</code>.
     */
    public final TableField<PokemonRecord, Short> EGG_VALUE = createField(DSL.name("egg_value"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.pokemon.hidden_power_type</code>.
     */
    public final TableField<PokemonRecord, Short> HIDDEN_POWER_TYPE = createField(DSL.name("hidden_power_type"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column
     * <code>public.pokemon.current_select_particle_effect_type</code>.
     */
    public final TableField<PokemonRecord, Short> CURRENT_SELECT_PARTICLE_EFFECT_TYPE = createField(DSL.name("current_select_particle_effect_type"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.pokemon.particle_effects</code>.
     */
    public final TableField<PokemonRecord, Short[]> PARTICLE_EFFECTS = createField(DSL.name("particle_effects"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::smallint[]"), SQLDataType.SMALLINT)).array(), this, "");

    private Pokemon(Name alias, Table<PokemonRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Pokemon(Name alias, Table<PokemonRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.pokemon</code> table reference
     */
    public Pokemon(String alias) {
        this(DSL.name(alias), POKEMON);
    }

    /**
     * Create an aliased <code>public.pokemon</code> table reference
     */
    public Pokemon(Name alias) {
        this(alias, POKEMON);
    }

    /**
     * Create a <code>public.pokemon</code> table reference
     */
    public Pokemon() {
        this(DSL.name("pokemon"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PokemonRecord, Long> getIdentity() {
        return (Identity<PokemonRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PokemonRecord> getPrimaryKey() {
        return Keys.POKEMON_PKEY;
    }

    @Override
    public Pokemon as(String alias) {
        return new Pokemon(DSL.name(alias), this);
    }

    @Override
    public Pokemon as(Name alias) {
        return new Pokemon(alias, this);
    }

    @Override
    public Pokemon as(Table<?> alias) {
        return new Pokemon(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Pokemon rename(String name) {
        return new Pokemon(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Pokemon rename(Name name) {
        return new Pokemon(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Pokemon rename(Table<?> name) {
        return new Pokemon(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pokemon where(Condition condition) {
        return new Pokemon(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pokemon where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pokemon where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pokemon where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pokemon where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pokemon where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pokemon where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pokemon where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pokemon whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pokemon whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
