/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.pokemmo.db.jooq.tables.Account;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.account.account_name</code>.
     */
    public void setAccountName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account.account_name</code>.
     */
    public String getAccountName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.account.password</code>.
     */
    public void setPassword(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.account.password</code>.
     */
    public byte[] getPassword() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>public.account.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.account.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.account.login_permission</code>.
     */
    public void setLoginPermission(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.account.login_permission</code>.
     */
    public Short getLoginPermission() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.account.ban_reason</code>.
     */
    public void setBanReason(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.account.ban_reason</code>.
     */
    public String getBanReason() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(Account.ACCOUNT);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(Integer accountId, String accountName, byte[] password, LocalDateTime createdAt, Short loginPermission, String banReason) {
        super(Account.ACCOUNT);

        setAccountId(accountId);
        setAccountName(accountName);
        setPassword(password);
        setCreatedAt(createdAt);
        setLoginPermission(loginPermission);
        setBanReason(banReason);
        resetChangedOnNotNull();
    }
}
