/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.pokemmo.db.jooq.tables.AccountContext;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountContextRecord extends UpdatableRecordImpl<AccountContextRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account_context.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account_context.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.account_context.character_id</code>.
     */
    public void setCharacterId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account_context.character_id</code>.
     */
    public Long getCharacterId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.account_context.game_node_id</code>.
     */
    public void setGameNodeId(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.account_context.game_node_id</code>.
     */
    public Short getGameNodeId() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.account_context.node_name</code>.
     */
    public void setNodeName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.account_context.node_name</code>.
     */
    public String getNodeName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.account_context.server_id</code>.
     */
    public void setServerId(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.account_context.server_id</code>.
     */
    public Short getServerId() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.account_context.is_log_out</code>.
     */
    public void setIsLogOut(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.account_context.is_log_out</code>.
     */
    public Boolean getIsLogOut() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.account_context.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.account_context.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountContextRecord
     */
    public AccountContextRecord() {
        super(AccountContext.ACCOUNT_CONTEXT);
    }

    /**
     * Create a detached, initialised AccountContextRecord
     */
    public AccountContextRecord(Integer accountId, Long characterId, Short gameNodeId, String nodeName, Short serverId, Boolean isLogOut, LocalDateTime updateAt) {
        super(AccountContext.ACCOUNT_CONTEXT);

        setAccountId(accountId);
        setCharacterId(characterId);
        setGameNodeId(gameNodeId);
        setNodeName(nodeName);
        setServerId(serverId);
        setIsLogOut(isLogOut);
        setUpdateAt(updateAt);
        resetChangedOnNotNull();
    }
}
