/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.pokemmo.db.jooq.tables.BlackList;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlackListRecord extends UpdatableRecordImpl<BlackListRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.black_list.player_id</code>.
     */
    public void setPlayerId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.black_list.player_id</code>.
     */
    public Long getPlayerId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.black_list.block_player_id</code>.
     */
    public void setBlockPlayerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.black_list.block_player_id</code>.
     */
    public Long getBlockPlayerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.black_list.block_time</code>.
     */
    public void setBlockTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.black_list.block_time</code>.
     */
    public LocalDateTime getBlockTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.black_list.block_player_name</code>.
     */
    public void setBlockPlayerName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.black_list.block_player_name</code>.
     */
    public String getBlockPlayerName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.black_list.block_reason</code>.
     */
    public void setBlockReason(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.black_list.block_reason</code>.
     */
    public String getBlockReason() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BlackListRecord
     */
    public BlackListRecord() {
        super(BlackList.BLACK_LIST);
    }

    /**
     * Create a detached, initialised BlackListRecord
     */
    public BlackListRecord(Long playerId, Long blockPlayerId, LocalDateTime blockTime, String blockPlayerName, String blockReason) {
        super(BlackList.BLACK_LIST);

        setPlayerId(playerId);
        setBlockPlayerId(blockPlayerId);
        setBlockTime(blockTime);
        setBlockPlayerName(blockPlayerName);
        setBlockReason(blockReason);
        resetChangedOnNotNull();
    }
}
