/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.pokemmo.db.jooq.tables.Character;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterRecord extends UpdatableRecordImpl<CharacterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.character.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.character.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.character.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.character.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.character.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.character.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.character.union_name</code>.
     */
    public void setUnionName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.character.union_name</code>.
     */
    public String getUnionName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.character.sex</code>.
     */
    public void setSex(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.character.sex</code>.
     */
    public Short getSex() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.character.login_time_stamp</code>.
     */
    public void setLoginTimeStamp(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.character.login_time_stamp</code>.
     */
    public LocalDateTime getLoginTimeStamp() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.character.last_login_mac</code>.
     */
    public void setLastLoginMac(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.character.last_login_mac</code>.
     */
    public Long getLastLoginMac() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.character.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.character.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.character.online_minutes</code>.
     */
    public void setOnlineMinutes(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.character.online_minutes</code>.
     */
    public Integer getOnlineMinutes() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.character.money</code>.
     */
    public void setMoney(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.character.money</code>.
     */
    public Integer getMoney() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.character.coins</code>.
     */
    public void setCoins(Short value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.character.coins</code>.
     */
    public Short getCoins() {
        return (Short) get(10);
    }

    /**
     * Setter for <code>public.character.battle_points</code>.
     */
    public void setBattlePoints(Short value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.character.battle_points</code>.
     */
    public Short getBattlePoints() {
        return (Short) get(11);
    }

    /**
     * Setter for <code>public.character.safari_steps</code>.
     */
    public void setSafariSteps(Short value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.character.safari_steps</code>.
     */
    public Short getSafariSteps() {
        return (Short) get(12);
    }

    /**
     * Setter for <code>public.character.safari_ball_amount</code>.
     */
    public void setSafariBallAmount(Short value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.character.safari_ball_amount</code>.
     */
    public Short getSafariBallAmount() {
        return (Short) get(13);
    }

    /**
     * Setter for <code>public.character.other_settings_value</code>.
     */
    public void setOtherSettingsValue(Short value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.character.other_settings_value</code>.
     */
    public Short getOtherSettingsValue() {
        return (Short) get(14);
    }

    /**
     * Setter for <code>public.character.pc_box_expansion_number</code>.
     */
    public void setPcBoxExpansionNumber(Short value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.character.pc_box_expansion_number</code>.
     */
    public Short getPcBoxExpansionNumber() {
        return (Short) get(15);
    }

    /**
     * Setter for <code>public.character.battle_box_expansion_number</code>.
     */
    public void setBattleBoxExpansionNumber(Short value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.character.battle_box_expansion_number</code>.
     */
    public Short getBattleBoxExpansionNumber() {
        return (Short) get(16);
    }

    /**
     * Setter for <code>public.character.template_amount</code>.
     */
    public void setTemplateAmount(Short value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.character.template_amount</code>.
     */
    public Short getTemplateAmount() {
        return (Short) get(17);
    }

    /**
     * Setter for <code>public.character.repel_steps</code>.
     */
    public void setRepelSteps(Short value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.character.repel_steps</code>.
     */
    public Short getRepelSteps() {
        return (Short) get(18);
    }

    /**
     * Setter for <code>public.character.repel_item_id</code>.
     */
    public void setRepelItemId(Short value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.character.repel_item_id</code>.
     */
    public Short getRepelItemId() {
        return (Short) get(19);
    }

    /**
     * Setter for <code>public.character.lure_type</code>.
     */
    public void setLureType(Short value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.character.lure_type</code>.
     */
    public Short getLureType() {
        return (Short) get(20);
    }

    /**
     * Setter for <code>public.character.lure_item_id</code>.
     */
    public void setLureItemId(Short value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.character.lure_item_id</code>.
     */
    public Short getLureItemId() {
        return (Short) get(21);
    }

    /**
     * Setter for <code>public.character.lure_steps</code>.
     */
    public void setLureSteps(Short value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.character.lure_steps</code>.
     */
    public Short getLureSteps() {
        return (Short) get(22);
    }

    /**
     * Setter for <code>public.character.region_id</code>.
     */
    public void setRegionId(Short value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.character.region_id</code>.
     */
    public Short getRegionId() {
        return (Short) get(23);
    }

    /**
     * Setter for
     * <code>public.character.map_header_id_or_gba_map_group_id</code>.
     */
    public void setMapHeaderIdOrGbaMapGroupId(Short value) {
        set(24, value);
    }

    /**
     * Getter for
     * <code>public.character.map_header_id_or_gba_map_group_id</code>.
     */
    public Short getMapHeaderIdOrGbaMapGroupId() {
        return (Short) get(24);
    }

    /**
     * Setter for <code>public.character.gba_map_id</code>.
     */
    public void setGbaMapId(Short value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.character.gba_map_id</code>.
     */
    public Short getGbaMapId() {
        return (Short) get(25);
    }

    /**
     * Setter for <code>public.character.x</code>.
     */
    public void setX(Short value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.character.x</code>.
     */
    public Short getX() {
        return (Short) get(26);
    }

    /**
     * Setter for <code>public.character.y</code>.
     */
    public void setY(Short value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.character.y</code>.
     */
    public Short getY() {
        return (Short) get(27);
    }

    /**
     * Setter for <code>public.character.z</code>.
     */
    public void setZ(Short value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.character.z</code>.
     */
    public Short getZ() {
        return (Short) get(28);
    }

    /**
     * Setter for <code>public.character.toward</code>.
     */
    public void setToward(Short value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.character.toward</code>.
     */
    public Short getToward() {
        return (Short) get(29);
    }

    /**
     * Setter for <code>public.character.transportation</code>.
     */
    public void setTransportation(Short value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.character.transportation</code>.
     */
    public Short getTransportation() {
        return (Short) get(30);
    }

    /**
     * Setter for <code>public.character.nameplate_status</code>.
     */
    public void setNameplateStatus(Short value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.character.nameplate_status</code>.
     */
    public Short getNameplateStatus() {
        return (Short) get(31);
    }

    /**
     * Setter for <code>public.character.permission</code>.
     */
    public void setPermission(Short value) {
        set(32, value);
    }

    /**
     * Getter for <code>public.character.permission</code>.
     */
    public Short getPermission() {
        return (Short) get(32);
    }

    /**
     * Setter for <code>public.character.model_region_index_id</code>.
     */
    public void setModelRegionIndexId(Short value) {
        set(33, value);
    }

    /**
     * Getter for <code>public.character.model_region_index_id</code>.
     */
    public Short getModelRegionIndexId() {
        return (Short) get(33);
    }

    /**
     * Setter for <code>public.character.model_index_id</code>.
     */
    public void setModelIndexId(Short value) {
        set(34, value);
    }

    /**
     * Getter for <code>public.character.model_index_id</code>.
     */
    public Short getModelIndexId() {
        return (Short) get(34);
    }

    /**
     * Setter for <code>public.character.follower_pokemon_index_id</code>.
     */
    public void setFollowerPokemonIndexId(Short value) {
        set(35, value);
    }

    /**
     * Getter for <code>public.character.follower_pokemon_index_id</code>.
     */
    public Short getFollowerPokemonIndexId() {
        return (Short) get(35);
    }

    /**
     * Setter for <code>public.character.follower_pokemon_rarity</code>.
     */
    public void setFollowerPokemonRarity(Short value) {
        set(36, value);
    }

    /**
     * Getter for <code>public.character.follower_pokemon_rarity</code>.
     */
    public Short getFollowerPokemonRarity() {
        return (Short) get(36);
    }

    /**
     * Setter for <code>public.character.forehead</code>.
     */
    public void setForehead(Short value) {
        set(37, value);
    }

    /**
     * Getter for <code>public.character.forehead</code>.
     */
    public Short getForehead() {
        return (Short) get(37);
    }

    /**
     * Setter for <code>public.character.forehead_color</code>.
     */
    public void setForeheadColor(Short value) {
        set(38, value);
    }

    /**
     * Getter for <code>public.character.forehead_color</code>.
     */
    public Short getForeheadColor() {
        return (Short) get(38);
    }

    /**
     * Setter for <code>public.character.hat</code>.
     */
    public void setHat(Short value) {
        set(39, value);
    }

    /**
     * Getter for <code>public.character.hat</code>.
     */
    public Short getHat() {
        return (Short) get(39);
    }

    /**
     * Setter for <code>public.character.hat_color</code>.
     */
    public void setHatColor(Short value) {
        set(40, value);
    }

    /**
     * Getter for <code>public.character.hat_color</code>.
     */
    public Short getHatColor() {
        return (Short) get(40);
    }

    /**
     * Setter for <code>public.character.hair</code>.
     */
    public void setHair(Short value) {
        set(41, value);
    }

    /**
     * Getter for <code>public.character.hair</code>.
     */
    public Short getHair() {
        return (Short) get(41);
    }

    /**
     * Setter for <code>public.character.hair_color</code>.
     */
    public void setHairColor(Short value) {
        set(42, value);
    }

    /**
     * Getter for <code>public.character.hair_color</code>.
     */
    public Short getHairColor() {
        return (Short) get(42);
    }

    /**
     * Setter for <code>public.character.eyes</code>.
     */
    public void setEyes(Short value) {
        set(43, value);
    }

    /**
     * Getter for <code>public.character.eyes</code>.
     */
    public Short getEyes() {
        return (Short) get(43);
    }

    /**
     * Setter for <code>public.character.eyes_color</code>.
     */
    public void setEyesColor(Short value) {
        set(44, value);
    }

    /**
     * Getter for <code>public.character.eyes_color</code>.
     */
    public Short getEyesColor() {
        return (Short) get(44);
    }

    /**
     * Setter for <code>public.character.facial_hair</code>.
     */
    public void setFacialHair(Short value) {
        set(45, value);
    }

    /**
     * Getter for <code>public.character.facial_hair</code>.
     */
    public Short getFacialHair() {
        return (Short) get(45);
    }

    /**
     * Setter for <code>public.character.facial_hair_color</code>.
     */
    public void setFacialHairColor(Short value) {
        set(46, value);
    }

    /**
     * Getter for <code>public.character.facial_hair_color</code>.
     */
    public Short getFacialHairColor() {
        return (Short) get(46);
    }

    /**
     * Setter for <code>public.character.back</code>.
     */
    public void setBack(Short value) {
        set(47, value);
    }

    /**
     * Getter for <code>public.character.back</code>.
     */
    public Short getBack() {
        return (Short) get(47);
    }

    /**
     * Setter for <code>public.character.back_color</code>.
     */
    public void setBackColor(Short value) {
        set(48, value);
    }

    /**
     * Getter for <code>public.character.back_color</code>.
     */
    public Short getBackColor() {
        return (Short) get(48);
    }

    /**
     * Setter for <code>public.character.top</code>.
     */
    public void setTop(Short value) {
        set(49, value);
    }

    /**
     * Getter for <code>public.character.top</code>.
     */
    public Short getTop() {
        return (Short) get(49);
    }

    /**
     * Setter for <code>public.character.top_color</code>.
     */
    public void setTopColor(Short value) {
        set(50, value);
    }

    /**
     * Getter for <code>public.character.top_color</code>.
     */
    public Short getTopColor() {
        return (Short) get(50);
    }

    /**
     * Setter for <code>public.character.gloves</code>.
     */
    public void setGloves(Short value) {
        set(51, value);
    }

    /**
     * Getter for <code>public.character.gloves</code>.
     */
    public Short getGloves() {
        return (Short) get(51);
    }

    /**
     * Setter for <code>public.character.gloves_color</code>.
     */
    public void setGlovesColor(Short value) {
        set(52, value);
    }

    /**
     * Getter for <code>public.character.gloves_color</code>.
     */
    public Short getGlovesColor() {
        return (Short) get(52);
    }

    /**
     * Setter for <code>public.character.footwear</code>.
     */
    public void setFootwear(Short value) {
        set(53, value);
    }

    /**
     * Getter for <code>public.character.footwear</code>.
     */
    public Short getFootwear() {
        return (Short) get(53);
    }

    /**
     * Setter for <code>public.character.footwear_color</code>.
     */
    public void setFootwearColor(Short value) {
        set(54, value);
    }

    /**
     * Getter for <code>public.character.footwear_color</code>.
     */
    public Short getFootwearColor() {
        return (Short) get(54);
    }

    /**
     * Setter for <code>public.character.leggings</code>.
     */
    public void setLeggings(Short value) {
        set(55, value);
    }

    /**
     * Getter for <code>public.character.leggings</code>.
     */
    public Short getLeggings() {
        return (Short) get(55);
    }

    /**
     * Setter for <code>public.character.leggings_color</code>.
     */
    public void setLeggingsColor(Short value) {
        set(56, value);
    }

    /**
     * Getter for <code>public.character.leggings_color</code>.
     */
    public Short getLeggingsColor() {
        return (Short) get(56);
    }

    /**
     * Setter for <code>public.character.fishing_rod</code>.
     */
    public void setFishingRod(Short value) {
        set(57, value);
    }

    /**
     * Getter for <code>public.character.fishing_rod</code>.
     */
    public Short getFishingRod() {
        return (Short) get(57);
    }

    /**
     * Setter for <code>public.character.bike</code>.
     */
    public void setBike(Short value) {
        set(58, value);
    }

    /**
     * Getter for <code>public.character.bike</code>.
     */
    public Short getBike() {
        return (Short) get(58);
    }

    /**
     * Setter for <code>public.character.champion_flag</code>.
     */
    public void setChampionFlag(Boolean[] value) {
        set(59, value);
    }

    /**
     * Getter for <code>public.character.champion_flag</code>.
     */
    public Boolean[] getChampionFlag() {
        return (Boolean[]) get(59);
    }

    /**
     * Setter for <code>public.character.running_shoe_flag</code>.
     */
    public void setRunningShoeFlag(Boolean[] value) {
        set(60, value);
    }

    /**
     * Getter for <code>public.character.running_shoe_flag</code>.
     */
    public Boolean[] getRunningShoeFlag() {
        return (Boolean[]) get(60);
    }

    /**
     * Setter for <code>public.character.badge_flag</code>.
     */
    public void setBadgeFlag(Short[] value) {
        set(61, value);
    }

    /**
     * Getter for <code>public.character.badge_flag</code>.
     */
    public Short[] getBadgeFlag() {
        return (Short[]) get(61);
    }

    /**
     * Setter for <code>public.character.story_line_flag</code>.
     */
    public void setStoryLineFlag(Short[] value) {
        set(62, value);
    }

    /**
     * Getter for <code>public.character.story_line_flag</code>.
     */
    public Short[] getStoryLineFlag() {
        return (Short[]) get(62);
    }

    /**
     * Setter for <code>public.character.city_can_fly_flag</code>.
     */
    public void setCityCanFlyFlag(Long[] value) {
        set(63, value);
    }

    /**
     * Getter for <code>public.character.city_can_fly_flag</code>.
     */
    public Long[] getCityCanFlyFlag() {
        return (Long[]) get(63);
    }

    /**
     * Setter for <code>public.character.instance_times</code>.
     */
    public void setInstanceTimes(Short[] value) {
        set(64, value);
    }

    /**
     * Getter for <code>public.character.instance_times</code>.
     */
    public Short[] getInstanceTimes() {
        return (Short[]) get(64);
    }

    /**
     * Setter for <code>public.character.instance_next_time</code>.
     */
    public void setInstanceNextTime(LocalDateTime[] value) {
        set(65, value);
    }

    /**
     * Getter for <code>public.character.instance_next_time</code>.
     */
    public LocalDateTime[] getInstanceNextTime() {
        return (LocalDateTime[]) get(65);
    }

    /**
     * Setter for <code>public.character.first_partner_status</code>.
     */
    public void setFirstPartnerStatus(Short[] value) {
        set(66, value);
    }

    /**
     * Getter for <code>public.character.first_partner_status</code>.
     */
    public Short[] getFirstPartnerStatus() {
        return (Short[]) get(66);
    }

    /**
     * Setter for <code>public.character.oak_lab_status</code>.
     */
    public void setOakLabStatus(Short value) {
        set(67, value);
    }

    /**
     * Getter for <code>public.character.oak_lab_status</code>.
     */
    public Short getOakLabStatus() {
        return (Short) get(67);
    }

    /**
     * Setter for <code>public.character.oak_parcel_status</code>.
     */
    public void setOakParcelStatus(Short value) {
        set(68, value);
    }

    /**
     * Getter for <code>public.character.oak_parcel_status</code>.
     */
    public Short getOakParcelStatus() {
        return (Short) get(68);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterRecord
     */
    public CharacterRecord() {
        super(Character.CHARACTER);
    }

    /**
     * Create a detached, initialised CharacterRecord
     */
    public CharacterRecord(Long id, Integer accountId, String name, String unionName, Short sex, LocalDateTime loginTimeStamp, Long lastLoginMac, LocalDateTime createdAt, Integer onlineMinutes, Integer money, Short coins, Short battlePoints, Short safariSteps, Short safariBallAmount, Short otherSettingsValue, Short pcBoxExpansionNumber, Short battleBoxExpansionNumber, Short templateAmount, Short repelSteps, Short repelItemId, Short lureType, Short lureItemId, Short lureSteps, Short regionId, Short mapHeaderIdOrGbaMapGroupId, Short gbaMapId, Short x, Short y, Short z, Short toward, Short transportation, Short nameplateStatus, Short permission, Short modelRegionIndexId, Short modelIndexId, Short followerPokemonIndexId, Short followerPokemonRarity, Short forehead, Short foreheadColor, Short hat, Short hatColor, Short hair, Short hairColor, Short eyes, Short eyesColor, Short facialHair, Short facialHairColor, Short back, Short backColor, Short top, Short topColor, Short gloves, Short glovesColor, Short footwear, Short footwearColor, Short leggings, Short leggingsColor, Short fishingRod, Short bike, Boolean[] championFlag, Boolean[] runningShoeFlag, Short[] badgeFlag, Short[] storyLineFlag, Long[] cityCanFlyFlag, Short[] instanceTimes, LocalDateTime[] instanceNextTime, Short[] firstPartnerStatus, Short oakLabStatus, Short oakParcelStatus) {
        super(Character.CHARACTER);

        setId(id);
        setAccountId(accountId);
        setName(name);
        setUnionName(unionName);
        setSex(sex);
        setLoginTimeStamp(loginTimeStamp);
        setLastLoginMac(lastLoginMac);
        setCreatedAt(createdAt);
        setOnlineMinutes(onlineMinutes);
        setMoney(money);
        setCoins(coins);
        setBattlePoints(battlePoints);
        setSafariSteps(safariSteps);
        setSafariBallAmount(safariBallAmount);
        setOtherSettingsValue(otherSettingsValue);
        setPcBoxExpansionNumber(pcBoxExpansionNumber);
        setBattleBoxExpansionNumber(battleBoxExpansionNumber);
        setTemplateAmount(templateAmount);
        setRepelSteps(repelSteps);
        setRepelItemId(repelItemId);
        setLureType(lureType);
        setLureItemId(lureItemId);
        setLureSteps(lureSteps);
        setRegionId(regionId);
        setMapHeaderIdOrGbaMapGroupId(mapHeaderIdOrGbaMapGroupId);
        setGbaMapId(gbaMapId);
        setX(x);
        setY(y);
        setZ(z);
        setToward(toward);
        setTransportation(transportation);
        setNameplateStatus(nameplateStatus);
        setPermission(permission);
        setModelRegionIndexId(modelRegionIndexId);
        setModelIndexId(modelIndexId);
        setFollowerPokemonIndexId(followerPokemonIndexId);
        setFollowerPokemonRarity(followerPokemonRarity);
        setForehead(forehead);
        setForeheadColor(foreheadColor);
        setHat(hat);
        setHatColor(hatColor);
        setHair(hair);
        setHairColor(hairColor);
        setEyes(eyes);
        setEyesColor(eyesColor);
        setFacialHair(facialHair);
        setFacialHairColor(facialHairColor);
        setBack(back);
        setBackColor(backColor);
        setTop(top);
        setTopColor(topColor);
        setGloves(gloves);
        setGlovesColor(glovesColor);
        setFootwear(footwear);
        setFootwearColor(footwearColor);
        setLeggings(leggings);
        setLeggingsColor(leggingsColor);
        setFishingRod(fishingRod);
        setBike(bike);
        setChampionFlag(championFlag);
        setRunningShoeFlag(runningShoeFlag);
        setBadgeFlag(badgeFlag);
        setStoryLineFlag(storyLineFlag);
        setCityCanFlyFlag(cityCanFlyFlag);
        setInstanceTimes(instanceTimes);
        setInstanceNextTime(instanceNextTime);
        setFirstPartnerStatus(firstPartnerStatus);
        setOakLabStatus(oakLabStatus);
        setOakParcelStatus(oakParcelStatus);
        resetChangedOnNotNull();
    }
}
