/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.pokemmo.db.jooq.tables.Container;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContainerRecord extends UpdatableRecordImpl<ContainerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.container.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.container.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.container.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.container.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.container.size</code>.
     */
    public void setSize(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.container.size</code>.
     */
    public Integer getSize() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.container.required</code>.
     */
    public void setRequired(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.container.required</code>.
     */
    public Boolean getRequired() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContainerRecord
     */
    public ContainerRecord() {
        super(Container.CONTAINER);
    }

    /**
     * Create a detached, initialised ContainerRecord
     */
    public ContainerRecord(Integer id, String name, Integer size, Boolean required) {
        super(Container.CONTAINER);

        setId(id);
        setName(name);
        setSize(size);
        setRequired(required);
        resetChangedOnNotNull();
    }
}
