/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.pokemmo.db.jooq.tables.FriendList;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FriendListRecord extends UpdatableRecordImpl<FriendListRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.friend_list.player_id</code>.
     */
    public void setPlayerId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.friend_list.player_id</code>.
     */
    public Long getPlayerId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.friend_list.friend_id</code>.
     */
    public void setFriendId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.friend_list.friend_id</code>.
     */
    public Long getFriendId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.friend_list.add_time</code>.
     */
    public void setAddTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.friend_list.add_time</code>.
     */
    public LocalDateTime getAddTime() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FriendListRecord
     */
    public FriendListRecord() {
        super(FriendList.FRIEND_LIST);
    }

    /**
     * Create a detached, initialised FriendListRecord
     */
    public FriendListRecord(Long playerId, Long friendId, LocalDateTime addTime) {
        super(FriendList.FRIEND_LIST);

        setPlayerId(playerId);
        setFriendId(friendId);
        setAddTime(addTime);
        resetChangedOnNotNull();
    }
}
