/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.pokemmo.db.jooq.tables.GameNode;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameNodeRecord extends UpdatableRecordImpl<GameNodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.game_node.node_id</code>.
     */
    public void setNodeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.game_node.node_id</code>.
     */
    public Integer getNodeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.game_node.node_type</code>.
     */
    public void setNodeType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.game_node.node_type</code>.
     */
    public String getNodeType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.game_node.node_name</code>.
     */
    public void setNodeName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.game_node.node_name</code>.
     */
    public String getNodeName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.game_node.port</code>.
     */
    public void setPort(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.game_node.port</code>.
     */
    public Integer getPort() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.game_node.permission_id</code>.
     */
    public void setPermissionId(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.game_node.permission_id</code>.
     */
    public Short getPermissionId() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.game_node.is_join_able</code>.
     */
    public void setIsJoinAble(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.game_node.is_join_able</code>.
     */
    public Boolean getIsJoinAble() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.game_node.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.game_node.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameNodeRecord
     */
    public GameNodeRecord() {
        super(GameNode.GAME_NODE);
    }

    /**
     * Create a detached, initialised GameNodeRecord
     */
    public GameNodeRecord(Integer nodeId, String nodeType, String nodeName, Integer port, Short permissionId, Boolean isJoinAble, LocalDateTime createdAt) {
        super(GameNode.GAME_NODE);

        setNodeId(nodeId);
        setNodeType(nodeType);
        setNodeName(nodeName);
        setPort(port);
        setPermissionId(permissionId);
        setIsJoinAble(isJoinAble);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
