/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.postgres.extensions.types.Inet;
import org.pokemmo.db.jooq.tables.OnlineGameNodeServer;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OnlineGameNodeServerRecord extends UpdatableRecordImpl<OnlineGameNodeServerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.online_game_node_server.server_id</code>.
     */
    public void setServerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.online_game_node_server.server_id</code>.
     */
    public Integer getServerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.online_game_node_server.node_id</code>.
     */
    public void setNodeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.online_game_node_server.node_id</code>.
     */
    public Integer getNodeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.online_game_node_server.ipv4</code>.
     */
    public void setIpv4(Inet value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.online_game_node_server.ipv4</code>.
     */
    public Inet getIpv4() {
        return (Inet) get(2);
    }

    /**
     * Setter for <code>public.online_game_node_server.ipv6</code>.
     */
    public void setIpv6(Inet value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.online_game_node_server.ipv6</code>.
     */
    public Inet getIpv6() {
        return (Inet) get(3);
    }

    /**
     * Setter for <code>public.online_game_node_server.port</code>.
     */
    public void setPort(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.online_game_node_server.port</code>.
     */
    public Integer getPort() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OnlineGameNodeServerRecord
     */
    public OnlineGameNodeServerRecord() {
        super(OnlineGameNodeServer.ONLINE_GAME_NODE_SERVER);
    }

    /**
     * Create a detached, initialised OnlineGameNodeServerRecord
     */
    public OnlineGameNodeServerRecord(Integer serverId, Integer nodeId, Inet ipv4, Inet ipv6, Integer port) {
        super(OnlineGameNodeServer.ONLINE_GAME_NODE_SERVER);

        setServerId(serverId);
        setNodeId(nodeId);
        setIpv4(ipv4);
        setIpv6(ipv6);
        setPort(port);
        resetChangedOnNotNull();
    }
}
