/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.pokemmo.db.jooq.tables.OwnedItem;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OwnedItemRecord extends UpdatableRecordImpl<OwnedItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.owned_item.item_id</code>.
     */
    public void setItemId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.owned_item.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.owned_item.owner_id</code>.
     */
    public void setOwnerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.owned_item.owner_id</code>.
     */
    public Long getOwnerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.owned_item.item_index_id</code>.
     */
    public void setItemIndexId(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.owned_item.item_index_id</code>.
     */
    public Short getItemIndexId() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.owned_item.item_amount</code>.
     */
    public void setItemAmount(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.owned_item.item_amount</code>.
     */
    public Short getItemAmount() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.owned_item.inventory_id</code>.
     */
    public void setInventoryId(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.owned_item.inventory_id</code>.
     */
    public Short getInventoryId() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.owned_item.color_id</code>.
     */
    public void setColorId(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.owned_item.color_id</code>.
     */
    public Short getColorId() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.owned_item.item_region_index_id</code>.
     */
    public void setItemRegionIndexId(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.owned_item.item_region_index_id</code>.
     */
    public Short getItemRegionIndexId() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.owned_item.pvp_reward_level</code>.
     */
    public void setPvpRewardLevel(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.owned_item.pvp_reward_level</code>.
     */
    public Short getPvpRewardLevel() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>public.owned_item.pvp_reward_season</code>.
     */
    public void setPvpRewardSeason(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.owned_item.pvp_reward_season</code>.
     */
    public Short getPvpRewardSeason() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>public.owned_item.pvp_reward_time</code>.
     */
    public void setPvpRewardTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.owned_item.pvp_reward_time</code>.
     */
    public LocalDateTime getPvpRewardTime() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OwnedItemRecord
     */
    public OwnedItemRecord() {
        super(OwnedItem.OWNED_ITEM);
    }

    /**
     * Create a detached, initialised OwnedItemRecord
     */
    public OwnedItemRecord(Long itemId, Long ownerId, Short itemIndexId, Short itemAmount, Short inventoryId, Short colorId, Short itemRegionIndexId, Short pvpRewardLevel, Short pvpRewardSeason, LocalDateTime pvpRewardTime) {
        super(OwnedItem.OWNED_ITEM);

        setItemId(itemId);
        setOwnerId(ownerId);
        setItemIndexId(itemIndexId);
        setItemAmount(itemAmount);
        setInventoryId(inventoryId);
        setColorId(colorId);
        setItemRegionIndexId(itemRegionIndexId);
        setPvpRewardLevel(pvpRewardLevel);
        setPvpRewardSeason(pvpRewardSeason);
        setPvpRewardTime(pvpRewardTime);
        resetChangedOnNotNull();
    }
}
