/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.pokemmo.db.jooq.tables.PokemonDex;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PokemonDexRecord extends UpdatableRecordImpl<PokemonDexRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pokemon_dex.player_id</code>.
     */
    public void setPlayerId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pokemon_dex.player_id</code>.
     */
    public Long getPlayerId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.pokemon_dex.meet_level</code>.
     */
    public void setMeetLevel(byte[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pokemon_dex.meet_level</code>.
     */
    public byte[] getMeetLevel() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>public.pokemon_dex.already_have_level</code>.
     */
    public void setAlreadyHaveLevel(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pokemon_dex.already_have_level</code>.
     */
    public byte[] getAlreadyHaveLevel() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>public.pokemon_dex.caught_level</code>.
     */
    public void setCaughtLevel(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pokemon_dex.caught_level</code>.
     */
    public byte[] getCaughtLevel() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>public.pokemon_dex.caught_alpha_level</code>.
     */
    public void setCaughtAlphaLevel(byte[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pokemon_dex.caught_alpha_level</code>.
     */
    public byte[] getCaughtAlphaLevel() {
        return (byte[]) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PokemonDexRecord
     */
    public PokemonDexRecord() {
        super(PokemonDex.POKEMON_DEX);
    }

    /**
     * Create a detached, initialised PokemonDexRecord
     */
    public PokemonDexRecord(Long playerId, byte[] meetLevel, byte[] alreadyHaveLevel, byte[] caughtLevel, byte[] caughtAlphaLevel) {
        super(PokemonDex.POKEMON_DEX);

        setPlayerId(playerId);
        setMeetLevel(meetLevel);
        setAlreadyHaveLevel(alreadyHaveLevel);
        setCaughtLevel(caughtLevel);
        setCaughtAlphaLevel(caughtAlphaLevel);
        resetChangedOnNotNull();
    }
}
