/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.pokemmo.db.jooq.tables.Pokemon;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PokemonRecord extends UpdatableRecordImpl<PokemonRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pokemon.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pokemon.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.pokemon.trainer_id</code>.
     */
    public void setTrainerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pokemon.trainer_id</code>.
     */
    public Long getTrainerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.pokemon.widget_type</code>.
     */
    public void setWidgetType(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pokemon.widget_type</code>.
     */
    public Short getWidgetType() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.pokemon.container_id</code>.
     */
    public void setContainerId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pokemon.container_id</code>.
     */
    public Integer getContainerId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.pokemon.container_position</code>.
     */
    public void setContainerPosition(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pokemon.container_position</code>.
     */
    public Short getContainerPosition() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.pokemon.dex_id</code>.
     */
    public void setDexId(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pokemon.dex_id</code>.
     */
    public Short getDexId() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.pokemon.personality_value</code>.
     */
    public void setPersonalityValue(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.pokemon.personality_value</code>.
     */
    public Integer getPersonalityValue() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.pokemon.original_trainer_id</code>.
     */
    public void setOriginalTrainerId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.pokemon.original_trainer_id</code>.
     */
    public Long getOriginalTrainerId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.pokemon.ot_name</code>.
     */
    public void setOtName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.pokemon.ot_name</code>.
     */
    public String getOtName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.pokemon.name</code>.
     */
    public void setName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.pokemon.name</code>.
     */
    public String getName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.pokemon.mark_status</code>.
     */
    public void setMarkStatus(Short value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.pokemon.mark_status</code>.
     */
    public Short getMarkStatus() {
        return (Short) get(10);
    }

    /**
     * Setter for <code>public.pokemon.status</code>.
     */
    public void setStatus(Short value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.pokemon.status</code>.
     */
    public Short getStatus() {
        return (Short) get(11);
    }

    /**
     * Setter for <code>public.pokemon.level_value</code>.
     */
    public void setLevelValue(Short value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.pokemon.level_value</code>.
     */
    public Short getLevelValue() {
        return (Short) get(12);
    }

    /**
     * Setter for <code>public.pokemon.current_hp</code>.
     */
    public void setCurrentHp(Short value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.pokemon.current_hp</code>.
     */
    public Short getCurrentHp() {
        return (Short) get(13);
    }

    /**
     * Setter for <code>public.pokemon.item</code>.
     */
    public void setItem(Short value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.pokemon.item</code>.
     */
    public Short getItem() {
        return (Short) get(14);
    }

    /**
     * Setter for <code>public.pokemon.exp</code>.
     */
    public void setExp(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.pokemon.exp</code>.
     */
    public Integer getExp() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.pokemon.pp_up_times</code>.
     */
    public void setPpUpTimes(Short value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.pokemon.pp_up_times</code>.
     */
    public Short getPpUpTimes() {
        return (Short) get(16);
    }

    /**
     * Setter for <code>public.pokemon.friend_value</code>.
     */
    public void setFriendValue(Short value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.pokemon.friend_value</code>.
     */
    public Short getFriendValue() {
        return (Short) get(17);
    }

    /**
     * Setter for <code>public.pokemon.moves</code>.
     */
    public void setMoves(Short[] value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.pokemon.moves</code>.
     */
    public Short[] getMoves() {
        return (Short[]) get(18);
    }

    /**
     * Setter for <code>public.pokemon.moves_pp</code>.
     */
    public void setMovesPp(Short[] value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.pokemon.moves_pp</code>.
     */
    public Short[] getMovesPp() {
        return (Short[]) get(19);
    }

    /**
     * Setter for <code>public.pokemon.can_remember_moves</code>.
     */
    public void setCanRememberMoves(Short[] value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.pokemon.can_remember_moves</code>.
     */
    public Short[] getCanRememberMoves() {
        return (Short[]) get(20);
    }

    /**
     * Setter for <code>public.pokemon.ev_values</code>.
     */
    public void setEvValues(Short[] value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.pokemon.ev_values</code>.
     */
    public Short[] getEvValues() {
        return (Short[]) get(21);
    }

    /**
     * Setter for <code>public.pokemon.contests_category_values</code>.
     */
    public void setContestsCategoryValues(Short[] value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.pokemon.contests_category_values</code>.
     */
    public Short[] getContestsCategoryValues() {
        return (Short[]) get(22);
    }

    /**
     * Setter for <code>public.pokemon.catch_address</code>.
     */
    public void setCatchAddress(Short value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.pokemon.catch_address</code>.
     */
    public Short getCatchAddress() {
        return (Short) get(23);
    }

    /**
     * Setter for <code>public.pokemon.catch_level</code>.
     */
    public void setCatchLevel(Short value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.pokemon.catch_level</code>.
     */
    public Short getCatchLevel() {
        return (Short) get(24);
    }

    /**
     * Setter for <code>public.pokemon.catch_region</code>.
     */
    public void setCatchRegion(Short value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.pokemon.catch_region</code>.
     */
    public Short getCatchRegion() {
        return (Short) get(25);
    }

    /**
     * Setter for <code>public.pokemon.ball_type</code>.
     */
    public void setBallType(Short value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.pokemon.ball_type</code>.
     */
    public Short getBallType() {
        return (Short) get(26);
    }

    /**
     * Setter for <code>public.pokemon.form_type</code>.
     */
    public void setFormType(Short value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.pokemon.form_type</code>.
     */
    public Short getFormType() {
        return (Short) get(27);
    }

    /**
     * Setter for <code>public.pokemon.iv_values</code>.
     */
    public void setIvValues(Short[] value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.pokemon.iv_values</code>.
     */
    public Short[] getIvValues() {
        return (Short[]) get(28);
    }

    /**
     * Setter for <code>public.pokemon.ability</code>.
     */
    public void setAbility(Short value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.pokemon.ability</code>.
     */
    public Short getAbility() {
        return (Short) get(29);
    }

    /**
     * Setter for <code>public.pokemon.contest_ribbon</code>.
     */
    public void setContestRibbon(Short[] value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.pokemon.contest_ribbon</code>.
     */
    public Short[] getContestRibbon() {
        return (Short[]) get(30);
    }

    /**
     * Setter for <code>public.pokemon.normal_ribbon</code>.
     */
    public void setNormalRibbon(Boolean[] value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.pokemon.normal_ribbon</code>.
     */
    public Boolean[] getNormalRibbon() {
        return (Boolean[]) get(31);
    }

    /**
     * Setter for <code>public.pokemon.has_hidden_ability</code>.
     */
    public void setHasHiddenAbility(Boolean value) {
        set(32, value);
    }

    /**
     * Getter for <code>public.pokemon.has_hidden_ability</code>.
     */
    public Boolean getHasHiddenAbility() {
        return (Boolean) get(32);
    }

    /**
     * Setter for <code>public.pokemon.is_shiny</code>.
     */
    public void setIsShiny(Boolean value) {
        set(33, value);
    }

    /**
     * Getter for <code>public.pokemon.is_shiny</code>.
     */
    public Boolean getIsShiny() {
        return (Boolean) get(33);
    }

    /**
     * Setter for <code>public.pokemon.is_alpha</code>.
     */
    public void setIsAlpha(Boolean value) {
        set(34, value);
    }

    /**
     * Getter for <code>public.pokemon.is_alpha</code>.
     */
    public Boolean getIsAlpha() {
        return (Boolean) get(34);
    }

    /**
     * Setter for <code>public.pokemon.is_secret</code>.
     */
    public void setIsSecret(Boolean value) {
        set(35, value);
    }

    /**
     * Getter for <code>public.pokemon.is_secret</code>.
     */
    public Boolean getIsSecret() {
        return (Boolean) get(35);
    }

    /**
     * Setter for <code>public.pokemon.catch_time</code>.
     */
    public void setCatchTime(LocalDateTime value) {
        set(36, value);
    }

    /**
     * Getter for <code>public.pokemon.catch_time</code>.
     */
    public LocalDateTime getCatchTime() {
        return (LocalDateTime) get(36);
    }

    /**
     * Setter for <code>public.pokemon.egg_value</code>.
     */
    public void setEggValue(Short value) {
        set(37, value);
    }

    /**
     * Getter for <code>public.pokemon.egg_value</code>.
     */
    public Short getEggValue() {
        return (Short) get(37);
    }

    /**
     * Setter for <code>public.pokemon.hidden_power_type</code>.
     */
    public void setHiddenPowerType(Short value) {
        set(38, value);
    }

    /**
     * Getter for <code>public.pokemon.hidden_power_type</code>.
     */
    public Short getHiddenPowerType() {
        return (Short) get(38);
    }

    /**
     * Setter for
     * <code>public.pokemon.current_select_particle_effect_type</code>.
     */
    public void setCurrentSelectParticleEffectType(Short value) {
        set(39, value);
    }

    /**
     * Getter for
     * <code>public.pokemon.current_select_particle_effect_type</code>.
     */
    public Short getCurrentSelectParticleEffectType() {
        return (Short) get(39);
    }

    /**
     * Setter for <code>public.pokemon.particle_effects</code>.
     */
    public void setParticleEffects(Short[] value) {
        set(40, value);
    }

    /**
     * Getter for <code>public.pokemon.particle_effects</code>.
     */
    public Short[] getParticleEffects() {
        return (Short[]) get(40);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PokemonRecord
     */
    public PokemonRecord() {
        super(Pokemon.POKEMON);
    }

    /**
     * Create a detached, initialised PokemonRecord
     */
    public PokemonRecord(Long id, Long trainerId, Short widgetType, Integer containerId, Short containerPosition, Short dexId, Integer personalityValue, Long originalTrainerId, String otName, String name, Short markStatus, Short status, Short levelValue, Short currentHp, Short item, Integer exp, Short ppUpTimes, Short friendValue, Short[] moves, Short[] movesPp, Short[] canRememberMoves, Short[] evValues, Short[] contestsCategoryValues, Short catchAddress, Short catchLevel, Short catchRegion, Short ballType, Short formType, Short[] ivValues, Short ability, Short[] contestRibbon, Boolean[] normalRibbon, Boolean hasHiddenAbility, Boolean isShiny, Boolean isAlpha, Boolean isSecret, LocalDateTime catchTime, Short eggValue, Short hiddenPowerType, Short currentSelectParticleEffectType, Short[] particleEffects) {
        super(Pokemon.POKEMON);

        setId(id);
        setTrainerId(trainerId);
        setWidgetType(widgetType);
        setContainerId(containerId);
        setContainerPosition(containerPosition);
        setDexId(dexId);
        setPersonalityValue(personalityValue);
        setOriginalTrainerId(originalTrainerId);
        setOtName(otName);
        setName(name);
        setMarkStatus(markStatus);
        setStatus(status);
        setLevelValue(levelValue);
        setCurrentHp(currentHp);
        setItem(item);
        setExp(exp);
        setPpUpTimes(ppUpTimes);
        setFriendValue(friendValue);
        setMoves(moves);
        setMovesPp(movesPp);
        setCanRememberMoves(canRememberMoves);
        setEvValues(evValues);
        setContestsCategoryValues(contestsCategoryValues);
        setCatchAddress(catchAddress);
        setCatchLevel(catchLevel);
        setCatchRegion(catchRegion);
        setBallType(ballType);
        setFormType(formType);
        setIvValues(ivValues);
        setAbility(ability);
        setContestRibbon(contestRibbon);
        setNormalRibbon(normalRibbon);
        setHasHiddenAbility(hasHiddenAbility);
        setIsShiny(isShiny);
        setIsAlpha(isAlpha);
        setIsSecret(isSecret);
        setCatchTime(catchTime);
        setEggValue(eggValue);
        setHiddenPowerType(hiddenPowerType);
        setCurrentSelectParticleEffectType(currentSelectParticleEffectType);
        setParticleEffects(particleEffects);
        resetChangedOnNotNull();
    }
}
