/*
 * This file is generated by jOOQ.
 */
package org.pokemmo.db.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.postgres.extensions.types.Inet;
import org.pokemmo.db.jooq.tables.ServerToken;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServerTokenRecord extends UpdatableRecordImpl<ServerTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.server_token.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.server_token.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.server_token.node_type</code>.
     */
    public void setNodeType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.server_token.node_type</code>.
     */
    public String getNodeType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.server_token.node_id</code>.
     */
    public void setNodeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.server_token.node_id</code>.
     */
    public Integer getNodeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.server_token.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.server_token.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.server_token.account_ip</code>.
     */
    public void setAccountIp(Inet value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.server_token.account_ip</code>.
     */
    public Inet getAccountIp() {
        return (Inet) get(4);
    }

    /**
     * Setter for <code>public.server_token.token_type</code>.
     */
    public void setTokenType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.server_token.token_type</code>.
     */
    public String getTokenType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.server_token.token</code>.
     */
    public void setToken(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.server_token.token</code>.
     */
    public UUID getToken() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>public.server_token.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.server_token.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServerTokenRecord
     */
    public ServerTokenRecord() {
        super(ServerToken.SERVER_TOKEN);
    }

    /**
     * Create a detached, initialised ServerTokenRecord
     */
    public ServerTokenRecord(Integer id, String nodeType, Integer nodeId, Integer accountId, Inet accountIp, String tokenType, UUID token, LocalDateTime createdAt) {
        super(ServerToken.SERVER_TOKEN);

        setId(id);
        setNodeType(nodeType);
        setNodeId(nodeId);
        setAccountId(accountId);
        setAccountIp(accountIp);
        setTokenType(tokenType);
        setToken(token);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
